package domains

// var Blocked = []string{
// 	"domain:knst.me",
// 	"domain:canva.com",
// 	"domain:canva.com.ru",
// 	"domain:cdninstagram.com",
// 	"domain:igcdn.com",
// 	"domain:fbcdn.net",
// 	"domain:microsoft.com",
// 	"domain:ggpht.com",
// 	"domain:seasonvar.ru",
// 	"domain:tuta.com",
// 	"domain:tuta.io",
// 	"domain:tutanota.com",
// 	"domain:tutanota.de",
// 	"domain:tutanota.org",
// 	"domain:tutamail.com",
// 	"domain:keemail.me",
// 	"domain:sndcdn.com",
// 	"domain:spotify.com",
// 	"domain:scdn.co",
// 	"domain:spotilocal.com",
// 	"domain:spotifycdn.com",
// 	"domain:spotifyedge.com",
// 	"domain:zahav.ru",
// 	"domain:vimeo.com",
// 	"domain:wildstat.ru",
// 	"domain:ytimg.com",
// 	"domain:imgur.com",
// 	"domain:amdm.ru",
// 	"domain:fitaudit.ru",
// 	"domain:2ip.ru",
// 	"domain:animespirit.ru",
// 	"domain:moscowtimes.ru",
// 	"domain:kasparov.ru",
// 	"domain:novayagazeta.ru",
// 	"domain:grani.ru",
// 	"domain:newtimes.ru",
// 	"domain:tvrain.ru",
// 	"domain:the-village.ru",
// 	"domain:arsvest.ru",
// 	"domain:zasekin.ru",
// 	"domain:trv-science.ru",
// 	"domain:snob.ru",
// 	"domain:colta.ru",
// 	"domain:newizv.ru",
// 	"domain:itsmycity.ru",
// 	"domain:theins.ru",
// 	"domain:4pda.ru",
// 	"domain:abook-club.ru",
// 	"domain:appstorrent.ru",
// 	"domain:ej.ru",
// 	"domain:onlinesim.ru",
// 	"domain:republic.ru",
// 	"domain:sobesednik.ru",
// 	"domain:polit.ru",
// 	"domain:te-st.ru",
// 	"domain:bestchange.ru",
// 	"domain:habr.com",
// 	"domain:habrastorage.org",
// 	"domain:onlinesim.io",
// 	"domain:adobe.com",
// 	"domain:canva.com",
// 	"domain:deepmind.com",
// 	"domain:deepmind.google",
// 	"domain:geller-pa.googleapis.com",
// 	"domain:generativelanguage.googleapis.com",
// 	"domain:proactivebackend-pa.googleapis.com",
// 	"domain:ai.google.dev",
// 	"domain:alkalicore-pa.clients6.google.com",
// 	"domain:alkalimakersuite-pa.clients6.google.com",
// 	"domain:generativeai.google",
// 	"domain:makersuite.google.com",
// 	"domain:aistudio.google.com",
// 	"domain:bard.google.com",
// 	"domain:gemini.google",
// 	"domain:gemini.google.com",
// 	"domain:rutracker.org",
// 	"habr.com",
// 	"4pda.to",
// 	"4pda.ru",
// 	"kemono.su",
// 	"jut.su",
// 	"kara.su",
// 	"theins.ru",
// 	"tvrain.ru",
// 	"echo.msk.ru",
// 	"the-village.ru",
// 	"snob.ru",
// 	"novayagazeta.ru",
// 	"moscowtimes.ru",
// 	"geosite:tiktok",
// 	"tiktok.com",
// 	"tiktokv.com",
// 	"tiktokv.eu",
// 	"tiktokv.us",
// 	"tiktokw.eu",
// 	"tiktokw.us",
// 	"tiktokcdn.com",
// 	"tiktokcdn-eu.com",
// 	"tiktokcdn-us.com",
// 	"tiktokeu-cdn.com",
// 	"tiktokrow-cdn.com",
// 	"tiktokd.net",
// 	"tiktokd.org",
// 	"tik-tokapi.com",
// 	"byteoversea.com",
// 	"bytedance.com",
// 	"byteimg.com",
// 	"ibytedtos.com",
// 	"muscdn.com",
// 	"musical.ly",
// 	"ttlivecdn.com",
// 	"ttoverseaus.net",
// 	"ttwstatic.com",
// 	"full:p16-tiktokcdn-com.akamaized.net",
// }

var RU = []string{
	"domain:ru",
	"domain:xn--p1ai",
	"domain:by",
	"domain:nnmclub.to",
	"domain:kinozal.tv",
	"keyword:nnmclub",
	"keyword:kinozal",
	"domain:animego.org",
	"domain:animego.me",
	"downdetector.info",
	"downdetector.su",
	"domain:yandex.com",
	"domain:yandex.by",
	"domain:yandex.net",
	"domain:yandex.org",
	"domain:yastatic.net",
	"domain:yandexcloud.net",
	"domain:yandex-bank.net",
	"domain:yandex.md",
	"domain:ymetrica1.com",
	"domain:naydex.net",
	"domain:ozonusercontent.com",
	"domain:sberbank.com",
	"domain:upravel.com",
	"domain:afp.ai",
	"domain:flocktory.com",
	"domain:wbstatic.net",
	"domain:vk.com",
	"domain:vktrk.com",
	"domain:vk-portal.net",
	"domain:mvk.com",
	"domain:userapi.com",
	"domain:vk-cdn.me",
	"domain:vk-cdn.net",
	"domain:vk.cc",
	"domain:vk.design",
	"domain:vk.link",
	"domain:vk.me",
	"domain:vkcache.com",
	"domain:vkgo.app",
	"domain:vklive.app",
	"domain:vkmessenger.com",
	"domain:vkmessenger.app",
	"domain:vkuseraudio.com",
	"domain:vkuseraudio.net",
	"domain:vkuserlive.net",
	"domain:vkuservideo.com",
	"domain:vkuservideo.net",
	"domain:vkuser.net",
	"domain:mycdn.me",
	"domain:2gis.com",
	"domain:lenta.com",
	"domain:gldn.net",
	"domain:avito.st",
	"domain:gismeteo.st",
	"domain:gismeteo.net",
	"domain:mradx.net",
	"domain:aestatic.net",
	"domain:pushwoosh.com",
	"domain:otm-r.com",
	"domain:championat.com",
	"domain:rus-tv.su",
	"domain:kpcdn.net",
	"domain:kp.house",
	"domain:kp.kg",
	"domain:kaspersky-labs.com",
	"domain:boosty.to",
	"domain:eaglecdn.com",
	"domain:livejournal.com",
	"domain:livejournal.net",
	"domain:d-cd.net",
	"domain:mayak.help",
	"domain:payselection.com",
	"domain:edc.sale",
	"domain:stellarlabs.ai",
	"domain:myminsk.com",
	"domain:sputniknews.com",
	"domain:sputnikglobe.com",
}
