services:
  beyondsecure-db:
    image: postgres:18.0-alpine3.22
    container_name: beyondsecure-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: beyondsecure
      POSTGRES_USER: root
      POSTGRES_PASSWORD: zoW6rZF274ufQHtJMhdCMbBoICv6KGWG
      PGDATA: /data/postgres
    ports:
      - 2345:5432
    volumes:
      - ./data:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d beyondsecure"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  beyondsecure-migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    container_name: beyondsecure-migrator
    command: migrate run --source /migrations
    environment:
      DATABASE_URL: postgres://root:zoW6rZF274ufQHtJMhdCMbBoICv6KGWG@beyondsecure-db:5432/beyondsecure
    volumes:
      - ./migrations:/migrations:ro
    depends_on:
      beyondsecure-db:
        condition: service_healthy
    restart: no