FROM rust:1.90.0-alpine3.22 AS builder

WORKDIR /usr/src/app

RUN apk add --no-cache musl-dev pkgconfig libressl-dev
RUN cargo install sqlx-cli --no-default-features --features rustls,postgres

FROM alpine:3.22
COPY --from=builder /usr/local/cargo/bin/sqlx /usr/local/bin/sqlx
WORKDIR /app
ENTRYPOINT ["sqlx"]
