CREATE TABLE IF NOT EXISTS promo (
    name TEXT NOT NULL PRIMARY KEY,
    creator INTEGER NOT NULL REFERENCES account ON DELETE CASCADE,
    level SMALLINT NOT NULL DEFAULT 1,
    discount_client SMALLINT NOT NULL DEFAULT 0,
    clients SMALLINT NOT NULL DEFAULT 0,
    buyers SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX promo_creator_idx ON promo (creator);

CREATE TABLE IF NOT EXISTS promo_buyer (
    promo TEXT NOT NULL REFERENCES promo ON DELETE CASCADE,
    fk_buyer_id INTEGER NOT NULL REFERENCES account ON DELETE CASCADE,
    PRIMARY KEY (promo, fk_buyer_id)
);

ALTER TABLE account ADD COLUMN promo TEXT REFERENCES promo ON DELETE CASCADE;
