// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_config.sql

package sqlc

import (
	"context"
)

const regenerateKey = `-- name: RegenerateKey :exec
UPDATE account SET key_id = $1
WHERE id = $2
`

type RegenerateKeyParams struct {
	KeyID string
	ID    int32
}

func (q *Queries) RegenerateKey(ctx context.Context, arg RegenerateKeyParams) error {
	_, err := q.db.Exec(ctx, regenerateKey, arg.KeyID, arg.ID)
	return err
}

const setCurrency = `-- name: SetCurrency :exec
UPDATE account SET currency = $1
WHERE id = $2
`

type SetCurrencyParams struct {
	Currency string
	ID       int32
}

func (q *Queries) SetCurrency(ctx context.Context, arg SetCurrencyParams) error {
	_, err := q.db.Exec(ctx, setCurrency, arg.Currency, arg.ID)
	return err
}

const setLanguage = `-- name: SetLanguage :exec
UPDATE account SET language = $1
WHERE id = $2
`

type SetLanguageParams struct {
	Language string
	ID       int32
}

func (q *Queries) SetLanguage(ctx context.Context, arg SetLanguageParams) error {
	_, err := q.db.Exec(ctx, setLanguage, arg.Language, arg.ID)
	return err
}

const setLocation = `-- name: SetLocation :exec
UPDATE account SET server_location = $1
WHERE id = $2
`

type SetLocationParams struct {
	ServerLocation string
	ID             int32
}

func (q *Queries) SetLocation(ctx context.Context, arg SetLocationParams) error {
	_, err := q.db.Exec(ctx, setLocation, arg.ServerLocation, arg.ID)
	return err
}

const setProtocol = `-- name: SetProtocol :exec
UPDATE account SET protocol = $1
WHERE id = $2
`

type SetProtocolParams struct {
	Protocol string
	ID       int32
}

func (q *Queries) SetProtocol(ctx context.Context, arg SetProtocolParams) error {
	_, err := q.db.Exec(ctx, setProtocol, arg.Protocol, arg.ID)
	return err
}

const setRegion = `-- name: SetRegion :exec
UPDATE account SET region = $1
WHERE id = $2
`

type SetRegionParams struct {
	Region string
	ID     int32
}

func (q *Queries) SetRegion(ctx context.Context, arg SetRegionParams) error {
	_, err := q.db.Exec(ctx, setRegion, arg.Region, arg.ID)
	return err
}
