// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discount.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const resetDiscount = `-- name: ResetDiscount :exec
UPDATE account SET discount = 0
WHERE id = $1
`

func (q *Queries) ResetDiscount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, resetDiscount, id)
	return err
}

const setDiscount = `-- name: SetDiscount :exec
UPDATE account SET discount = $1
WHERE id = $2
`

type SetDiscountParams struct {
	Discount pgtype.Int4
	ID       int32
}

func (q *Queries) SetDiscount(ctx context.Context, arg SetDiscountParams) error {
	_, err := q.db.Exec(ctx, setDiscount, arg.Discount, arg.ID)
	return err
}
