// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessStatus string

const (
	AccessStatusAvailable   AccessStatus = "available"
	AccessStatusUnavailable AccessStatus = "unavailable"
)

func (e *AccessStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessStatus(s)
	case string:
		*e = AccessStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessStatus: %T", src)
	}
	return nil
}

type NullAccessStatus struct {
	AccessStatus AccessStatus
	Valid        bool // Valid is true if AccessStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccessStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessStatus), nil
}

type Account struct {
	ID                    int32
	KeyID                 string
	ShortID               string
	SubscriptionExpiresAt pgtype.Timestamptz
	Region                string
	Language              string
	Currency              string
	Protocol              string
	ServerLocation        string
	LastKeyRefreshAt      pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	Promo                 pgtype.Text
	Discount              pgtype.Int4
	ClusterID             pgtype.Int2
	ServiceCheckSent      pgtype.Int2
	Tariff                int16
	Devices               pgtype.Int2
	UsedUplink            int64
	UsedDownlink          int64
	FreemiumStatus        AccessStatus
	SubscriptionStatus    AccessStatus
	IsDisabled            bool
	LastTrafficRefreshAt  pgtype.Timestamptz
}

type Payment struct {
	AccountID int32
	Amount    int32
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type PlatformAccount struct {
	PlatformID        int16
	ExternalAccountID int64
	FkAccountID       int32
}

type Promo struct {
	Name           string
	Creator        int32
	Level          int16
	DiscountClient int16
	Clients        int16
	Buyers         int16
	CreatedAt      pgtype.Timestamp
}

type PromoBuyer struct {
	Promo     string
	FkBuyerID int32
}
