// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    int32
	KeyID                 string
	ShortID               string
	SubscriptionExpiresAt pgtype.Timestamptz
	Region                string
	Language              string
	Currency              string
	Protocol              string
	ServerLocation        string
	LastKeyRefreshAt      pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	Promo                 pgtype.Text
	Discount              pgtype.Int4
	ClusterID             pgtype.Int2
	ServiceCheckSent      pgtype.Int2
}

type Payment struct {
	AccountID int32
	Amount    int32
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type PlatformAccount struct {
	PlatformID        int16
	ExternalAccountID int64
	FkAccountID       int32
}

type Promo struct {
	Name           string
	Creator        int32
	Level          int16
	DiscountClient int16
	Clients        int16
	Buyers         int16
	CreatedAt      pgtype.Timestamp
}

type PromoBuyer struct {
	Promo     string
	FkBuyerID int32
}
