// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payment (account_id, amount, expires_at)
VALUES($1, $2, $3)
`

type CreatePaymentParams struct {
	AccountID int32
	Amount    int32
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.Exec(ctx, createPayment, arg.AccountID, arg.Amount, arg.ExpiresAt)
	return err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payment
WHERE account_id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deletePayment, accountID)
	return err
}

const getPayments = `-- name: GetPayments :many
SELECT amount, created_at, expires_at
FROM payment
WHERE account_id = $1
AND expires_at > NOW()
`

type GetPaymentsRow struct {
	Amount    int32
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetPayments(ctx context.Context, accountID int32) ([]GetPaymentsRow, error) {
	rows, err := q.db.Query(ctx, getPayments, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentsRow
	for rows.Next() {
		var i GetPaymentsRow
		if err := rows.Scan(&i.Amount, &i.CreatedAt, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
