// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promo.sql

package sqlc

import (
	"context"
)

const createPromo = `-- name: CreatePromo :exec
INSERT INTO promo (name, creator) VALUES ($1, $2)
`

type CreatePromoParams struct {
	Name    string
	Creator int32
}

func (q *Queries) CreatePromo(ctx context.Context, arg CreatePromoParams) error {
	_, err := q.db.Exec(ctx, createPromo, arg.Name, arg.Creator)
	return err
}

const getPromo = `-- name: GetPromo :one
SELECT
    name,
    creator,
    level,
    clients
FROM promo
WHERE name = $1
`

type GetPromoRow struct {
	Name    string
	Creator int32
	Level   int16
	Clients int16
}

func (q *Queries) GetPromo(ctx context.Context, name string) (GetPromoRow, error) {
	row := q.db.QueryRow(ctx, getPromo, name)
	var i GetPromoRow
	err := row.Scan(
		&i.Name,
		&i.Creator,
		&i.Level,
		&i.Clients,
	)
	return i, err
}

const getPromosByCreator = `-- name: GetPromosByCreator :many
SELECT
    name,
    creator,
    level,
    clients
FROM promo
WHERE creator = $1
`

type GetPromosByCreatorRow struct {
	Name    string
	Creator int32
	Level   int16
	Clients int16
}

func (q *Queries) GetPromosByCreator(ctx context.Context, creator int32) ([]GetPromosByCreatorRow, error) {
	rows, err := q.db.Query(ctx, getPromosByCreator, creator)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPromosByCreatorRow
	for rows.Next() {
		var i GetPromosByCreatorRow
		if err := rows.Scan(
			&i.Name,
			&i.Creator,
			&i.Level,
			&i.Clients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increasePromoClients = `-- name: IncreasePromoClients :exec
UPDATE promo SET clients = clients + 1
WHERE name = $1
`

func (q *Queries) IncreasePromoClients(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, increasePromoClients, name)
	return err
}

const upgradePromoLevel = `-- name: UpgradePromoLevel :exec
UPDATE promo SET level = level + 1, clients = 0
WHERE name = $1
`

func (q *Queries) UpgradePromoLevel(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, upgradePromoLevel, name)
	return err
}
