// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscription.sql

package sqlc

import (
	"context"
)

const addSubscriptionExpiresAt = `-- name: AddSubscriptionExpiresAt :exec
UPDATE account
SET subscription_expires_at = COALESCE(subscription_expires_at, NOW()) + make_interval(secs => $1)
WHERE id = $2
`

type AddSubscriptionExpiresAtParams struct {
	Secs float64
	ID   int32
}

func (q *Queries) AddSubscriptionExpiresAt(ctx context.Context, arg AddSubscriptionExpiresAtParams) error {
	_, err := q.db.Exec(ctx, addSubscriptionExpiresAt, arg.Secs, arg.ID)
	return err
}

const cancelSubscriptions = `-- name: CancelSubscriptions :exec
UPDATE account
SET subscription_expires_at = NULL
WHERE id = $1
`

func (q *Queries) CancelSubscriptions(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelSubscriptions, id)
	return err
}

const removeSubscriptionExpiresAt = `-- name: RemoveSubscriptionExpiresAt :exec
UPDATE account
SET subscription_expires_at = COALESCE(subscription_expires_at, NOW()) - make_interval(secs => $1)
WHERE id = $2
`

type RemoveSubscriptionExpiresAtParams struct {
	Secs float64
	ID   int32
}

func (q *Queries) RemoveSubscriptionExpiresAt(ctx context.Context, arg RemoveSubscriptionExpiresAtParams) error {
	_, err := q.db.Exec(ctx, removeSubscriptionExpiresAt, arg.Secs, arg.ID)
	return err
}
