// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xraynode/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClientRequest) Reset() {
	*x = AddClientRequest{}
	mi := &file_xraynode_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClientRequest) ProtoMessage() {}

func (x *AddClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xraynode_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClientRequest.ProtoReflect.Descriptor instead.
func (*AddClientRequest) Descriptor() ([]byte, []int) {
	return file_xraynode_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *AddClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddClientRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type RemoveClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClientRequest) Reset() {
	*x = RemoveClientRequest{}
	mi := &file_xraynode_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientRequest) ProtoMessage() {}

func (x *RemoveClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xraynode_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientRequest.ProtoReflect.Descriptor instead.
func (*RemoveClientRequest) Descriptor() ([]byte, []int) {
	return file_xraynode_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClientResponse) Reset() {
	*x = AddClientResponse{}
	mi := &file_xraynode_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClientResponse) ProtoMessage() {}

func (x *AddClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xraynode_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClientResponse.ProtoReflect.Descriptor instead.
func (*AddClientResponse) Descriptor() ([]byte, []int) {
	return file_xraynode_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *AddClientResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RemoveClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClientResponse) Reset() {
	*x = RemoveClientResponse{}
	mi := &file_xraynode_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientResponse) ProtoMessage() {}

func (x *RemoveClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xraynode_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientResponse.ProtoReflect.Descriptor instead.
func (*RemoveClientResponse) Descriptor() ([]byte, []int) {
	return file_xraynode_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveClientResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_xraynode_v1_message_proto protoreflect.FileDescriptor

const file_xraynode_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x19xraynode/v1/message.proto\x12\vxraynode.v1\"N\n" +
	"\x10AddClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\"+\n" +
	"\x13RemoveClientRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"#\n" +
	"\x11AddClientResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"&\n" +
	"\x14RemoveClientResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02okB\xa4\x01\n" +
	"\x0fcom.xraynode.v1B\fMessageProtoP\x01Z6github.com/quickpowered/thebeyond-node/pkg/xraynode/v1\xa2\x02\x03XXX\xaa\x02\vXraynode.V1\xca\x02\vXraynode\\V1\xe2\x02\x17Xraynode\\V1\\GPBMetadata\xea\x02\fXraynode::V1b\x06proto3"

var (
	file_xraynode_v1_message_proto_rawDescOnce sync.Once
	file_xraynode_v1_message_proto_rawDescData []byte
)

func file_xraynode_v1_message_proto_rawDescGZIP() []byte {
	file_xraynode_v1_message_proto_rawDescOnce.Do(func() {
		file_xraynode_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xraynode_v1_message_proto_rawDesc), len(file_xraynode_v1_message_proto_rawDesc)))
	})
	return file_xraynode_v1_message_proto_rawDescData
}

var file_xraynode_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xraynode_v1_message_proto_goTypes = []any{
	(*AddClientRequest)(nil),     // 0: xraynode.v1.AddClientRequest
	(*RemoveClientRequest)(nil),  // 1: xraynode.v1.RemoveClientRequest
	(*AddClientResponse)(nil),    // 2: xraynode.v1.AddClientResponse
	(*RemoveClientResponse)(nil), // 3: xraynode.v1.RemoveClientResponse
}
var file_xraynode_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xraynode_v1_message_proto_init() }
func file_xraynode_v1_message_proto_init() {
	if File_xraynode_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xraynode_v1_message_proto_rawDesc), len(file_xraynode_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xraynode_v1_message_proto_goTypes,
		DependencyIndexes: file_xraynode_v1_message_proto_depIdxs,
		MessageInfos:      file_xraynode_v1_message_proto_msgTypes,
	}.Build()
	File_xraynode_v1_message_proto = out.File
	file_xraynode_v1_message_proto_goTypes = nil
	file_xraynode_v1_message_proto_depIdxs = nil
}
