// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xraynode/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xraynode_v1_service_proto protoreflect.FileDescriptor

const file_xraynode_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19xraynode/v1/service.proto\x12\vxraynode.v1\x1a\x19xraynode/v1/message.proto2\xb2\x01\n" +
	"\vNodeService\x12L\n" +
	"\tAddClient\x12\x1d.xraynode.v1.AddClientRequest\x1a\x1e.xraynode.v1.AddClientResponse\"\x00\x12U\n" +
	"\fRemoveClient\x12 .xraynode.v1.RemoveClientRequest\x1a!.xraynode.v1.RemoveClientResponse\"\x00B\xa4\x01\n" +
	"\x0fcom.xraynode.v1B\fServiceProtoP\x01Z6github.com/quickpowered/thebeyond-node/pkg/xraynode/v1\xa2\x02\x03XXX\xaa\x02\vXraynode.V1\xca\x02\vXraynode\\V1\xe2\x02\x17Xraynode\\V1\\GPBMetadata\xea\x02\fXraynode::V1b\x06proto3"

var file_xraynode_v1_service_proto_goTypes = []any{
	(*AddClientRequest)(nil),     // 0: xraynode.v1.AddClientRequest
	(*RemoveClientRequest)(nil),  // 1: xraynode.v1.RemoveClientRequest
	(*AddClientResponse)(nil),    // 2: xraynode.v1.AddClientResponse
	(*RemoveClientResponse)(nil), // 3: xraynode.v1.RemoveClientResponse
}
var file_xraynode_v1_service_proto_depIdxs = []int32{
	0, // 0: xraynode.v1.NodeService.AddClient:input_type -> xraynode.v1.AddClientRequest
	1, // 1: xraynode.v1.NodeService.RemoveClient:input_type -> xraynode.v1.RemoveClientRequest
	2, // 2: xraynode.v1.NodeService.AddClient:output_type -> xraynode.v1.AddClientResponse
	3, // 3: xraynode.v1.NodeService.RemoveClient:output_type -> xraynode.v1.RemoveClientResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xraynode_v1_service_proto_init() }
func file_xraynode_v1_service_proto_init() {
	if File_xraynode_v1_service_proto != nil {
		return
	}
	file_xraynode_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xraynode_v1_service_proto_rawDesc), len(file_xraynode_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xraynode_v1_service_proto_goTypes,
		DependencyIndexes: file_xraynode_v1_service_proto_depIdxs,
	}.Build()
	File_xraynode_v1_service_proto = out.File
	file_xraynode_v1_service_proto_goTypes = nil
	file_xraynode_v1_service_proto_depIdxs = nil
}
