// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: xraynode/v1/service.proto

package v1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/quickpowered/thebeyond-master/pkg/xraynode/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "xraynode.v1.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceAddClientProcedure is the fully-qualified name of the NodeService's AddClient RPC.
	NodeServiceAddClientProcedure = "/xraynode.v1.NodeService/AddClient"
	// NodeServiceRemoveClientProcedure is the fully-qualified name of the NodeService's RemoveClient
	// RPC.
	NodeServiceRemoveClientProcedure = "/xraynode.v1.NodeService/RemoveClient"
)

// NodeServiceClient is a client for the xraynode.v1.NodeService service.
type NodeServiceClient interface {
	AddClient(context.Context, *v1.AddClientRequest) (*v1.AddClientResponse, error)
	RemoveClient(context.Context, *v1.RemoveClientRequest) (*v1.RemoveClientResponse, error)
}

// NewNodeServiceClient constructs a client for the xraynode.v1.NodeService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := v1.File_xraynode_v1_service_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		addClient: connect.NewClient[v1.AddClientRequest, v1.AddClientResponse](
			httpClient,
			baseURL+NodeServiceAddClientProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("AddClient")),
			connect.WithClientOptions(opts...),
		),
		removeClient: connect.NewClient[v1.RemoveClientRequest, v1.RemoveClientResponse](
			httpClient,
			baseURL+NodeServiceRemoveClientProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("RemoveClient")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	addClient    *connect.Client[v1.AddClientRequest, v1.AddClientResponse]
	removeClient *connect.Client[v1.RemoveClientRequest, v1.RemoveClientResponse]
}

// AddClient calls xraynode.v1.NodeService.AddClient.
func (c *nodeServiceClient) AddClient(ctx context.Context, req *v1.AddClientRequest) (*v1.AddClientResponse, error) {
	response, err := c.addClient.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RemoveClient calls xraynode.v1.NodeService.RemoveClient.
func (c *nodeServiceClient) RemoveClient(ctx context.Context, req *v1.RemoveClientRequest) (*v1.RemoveClientResponse, error) {
	response, err := c.removeClient.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// NodeServiceHandler is an implementation of the xraynode.v1.NodeService service.
type NodeServiceHandler interface {
	AddClient(context.Context, *v1.AddClientRequest) (*v1.AddClientResponse, error)
	RemoveClient(context.Context, *v1.RemoveClientRequest) (*v1.RemoveClientResponse, error)
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := v1.File_xraynode_v1_service_proto.Services().ByName("NodeService").Methods()
	nodeServiceAddClientHandler := connect.NewUnaryHandlerSimple(
		NodeServiceAddClientProcedure,
		svc.AddClient,
		connect.WithSchema(nodeServiceMethods.ByName("AddClient")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRemoveClientHandler := connect.NewUnaryHandlerSimple(
		NodeServiceRemoveClientProcedure,
		svc.RemoveClient,
		connect.WithSchema(nodeServiceMethods.ByName("RemoveClient")),
		connect.WithHandlerOptions(opts...),
	)
	return "/xraynode.v1.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceAddClientProcedure:
			nodeServiceAddClientHandler.ServeHTTP(w, r)
		case NodeServiceRemoveClientProcedure:
			nodeServiceRemoveClientHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) AddClient(context.Context, *v1.AddClientRequest) (*v1.AddClientResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xraynode.v1.NodeService.AddClient is not implemented"))
}

func (UnimplementedNodeServiceHandler) RemoveClient(context.Context, *v1.RemoveClientRequest) (*v1.RemoveClientResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xraynode.v1.NodeService.RemoveClient is not implemented"))
}
