package components

const ACCOUNT_COMPONENT = "account"

type AccountComponent struct {
	text map[string][]string
}

func NewAccountComponent() *AccountComponent {
	text := map[string][]string{
		"en": {
			"Your account",
			"Key",
			"Remaining",
			"Subscription expired",
			"No subscription",
		},
		"de": {
			"Ihr Konto",
			"Schlüssel",
			"Verbleibend",
			"Abonnement abgelaufen",
			"Kein Abonnement",
		},
		"nl": {
			"Uw account",
			"Sleutel",
			"Resterend",
			"Abonnement verlopen",
			"Geen abonnement",
		},
		"sv": {
			"Ditt konto",
			"Nyckel",
			"Återstående",
			"Prenumerationen har upphört",
			"Ingen prenumeration",
		},
		"no": {
			"Din konto",
			"Nøkkel",
			"Gjenværende",
			"Abonnement utløpt",
			"Ingen abonnement",
		},
		"da": {
			"Din konto",
			"Nøgle",
			"Tilbage",
			"Abonnement udløbet",
			"Intet abonnement",
		},
		"es": {
			"Tu cuenta",
			"Clave",
			"Restante",
			"Suscripción caducada",
			"Sin suscripción",
		},
		"fr": {
			"Votre compte",
			"Clé",
			"Restant",
			"Abonnement expiré",
			"Pas d'abonnement",
		},
		"pt": {
			"Sua conta",
			"Chave",
			"Restante",
			"Assinatura expirada",
			"Sem assinatura",
		},
		"it": {
			"Il tuo account",
			"Chiave",
			"Rimanente",
			"Abbonamento scaduto",
			"Nessun abbonamento",
		},
		"ru": {
			"Ваш аккаунт",
			"Ключ",
			"Осталось",
			"Подписка истекла",
			"Нет подписки",
		},
		"ua": {
			"Ваш обліковий запис",
			"Ключ",
			"Залишилося",
			"Підписка закінчилася",
			"Немає підписки",
		},
		"pl": {
			"Twoje konto",
			"Klucz",
			"Pozostało",
			"Subskrypcja wygasła",
			"Brak subskrypcji",
		},
		"cs": {
			"Váš účet",
			"Klíč",
			"Zbývající",
			"Předplatné vypršelo",
			"Žádné předplatné",
		},
		"bg": {
			"Вашият акаунт",
			"Ключ",
			"Оставащи",
			"Абонаментът изтече",
			"Няма абонамент",
		},
		"sr": {
			"Vaš nalog",
			"Ključ",
			"Preostalo",
			"Pretplata istekla",
			"Nema pretplate",
		},
		"hr": {
			"Vaš račun",
			"Ključ",
			"Preostalo",
			"Pretplata istekla",
			"Nema pretplate",
		},
		"sk": {
			"Váš účet",
			"Kľúč",
			"Zostávajúce",
			"Predplatné vypršalo",
			"Žiadne predplatné",
		},
		"sl": {
			"Vaš račun",
			"Ključ",
			"Preostalo",
			"Naročnina potekla",
			"Brez naročnine",
		},
		"lt": {
			"Jūsų paskyra",
			"Raktas",
			"Likęs",
			"Prenumerata baigėsi",
			"Nėra prenumeratos",
		},
		"lv": {
			"Jūsu konts",
			"Atslēga",
			"Atlikušais",
			"Abonements beidzies",
			"Nav abonementa",
		},
		"et": {
			"Teie konto",
			"Võti",
			"Järelejäänud",
			"Tellimus aegunud",
			"Tellimust pole",
		},
		"fi": {
			"Tilisi",
			"Avain",
			"Jäljellä",
			"Tilaus vanhentunut",
			"Ei tilausta",
		},
		"el": {
			"Ο λογαριασμός σας",
			"Κλειδί",
			"Υπόλοιπο",
			"Η συνδρομή έληξε",
			"Καμία συνδρομή",
		},
		"ro": {
			"Contul tău",
			"Cheie",
			"Rămas",
			"Abonament expirat",
			"Fără abonament",
		},
		"hu": {
			"Fiókod",
			"Kulcs",
			"Hátralévő",
			"Előfizetés lejárt",
			"Nincs előfizetés",
		},
		"ar": {
			"حسابك",
			"مفتاح",
			"المتبقي",
			"انتهت صلاحية الاشتراك",
			"لا اشتراك",
		},
		"fa": {
			"حساب شما",
			"کلید",
			"باقی مانده",
			"اشتراک منقضی شده",
			"بدون اشتراک",
		},
		"tr": {
			"Hesabınız",
			"Anahtar",
			"Kalan",
			"Abonelik süresi doldu",
			"Abonelik yok",
		},
		"he": {
			"החשבון שלך",
			"מפתח",
			"נותר",
			"המנוי פג",
			"אין מנוי",
		},
		"zh": {
			"您的帐户",
			"密钥",
			"剩余",
			"订阅已过期",
			"无订阅",
		},
		"ja": {
			"あなたのアカウント",
			"キー",
			"残り",
			"サブスクリプションが期限切れ",
			"サブスクリプションなし",
		},
		"ko": {
			"귀하의 계정",
			"키",
			"남은",
			"구독 만료됨",
			"구독 없음",
		},
		"vi": {
			"Tài khoản của bạn",
			"Khóa",
			"Còn lại",
			"Đăng ký đã hết hạn",
			"Không có đăng ký",
		},
		"th": {
			"บัญชีของคุณ",
			"คีย์",
			"ที่เหลือ",
			"การสมัครสมาชิกหมดอายุ",
			"ไม่มีการสมัครสมาชิก",
		},
		"id": {
			"Akun Anda",
			"Kunci",
			"Sisa",
			"Langganan kedaluwarsa",
			"Tidak ada langganan",
		},
		"ms": {
			"Akaun anda",
			"Kunci",
			"Baki",
			"Langganan tamat tempoh",
			"Tiada langganan",
		},
		"tl": {
			"Iyong account",
			"Susi",
			"Natitira",
			"Nag-expire ang subscription",
			"Walang subscription",
		},
		"hi": {
			"आपका खाता",
			"कुंजी",
			"शेष",
			"सदस्यता समाप्त हो गई",
			"कोई सदस्यता नहीं",
		},
		"ur": {
			"آپ کا اکاؤنٹ",
			"کلیدی",
			"باقی",
			"سبسکرپشن ختم ہو گئی",
			"کوئی سبسکرپشن نہیں",
		},
		"bn": {
			"আপনার অ্যাকাউন্ট",
			"চাবি",
			"অবশিষ্ট",
			"সাবস্ক্রিপশন মেয়াদ উত্তীর্ণ",
			"কোনো সাবস্ক্রিপশন নেই",
		},
		"ta": {
			"உங்கள் கணக்கு",
			"சாவி",
			"மீதமுள்ள",
			"சந்தா காலாவதியானது",
			"சந்தா இல்லை",
		},
		"te": {
			"మీ ఖాతా",
			"కీ",
			"మిగిలిన",
			"సబ్‌స్క్రిప్షన్ గడువు ముగిసింది",
			"సబ్‌స్క్రిప్షన్ లేదు",
		},
		"mr": {
			"तुमचे खाते",
			"की",
			"उरलेले",
			"सदस्यता कालबाह्य झाली",
			"सदस्यता नाही",
		},
	}

	return &AccountComponent{text}
}

func (c *AccountComponent) Text(language string) []string {
	return c.text[language]
}
