package components

const INVOICE_COMPONENT = "invoice"

type RefundComponent struct {
	text map[string][]string
}

func NewRefundComponent() *RefundComponent {
	text := map[string][]string{
		"en": {
			"<b>How does the refund work?</b>\nThe refund is processed in the local currency \"Stars\". The funds will be returned by the creator under the post in your Telegram channel.\n\n<b>Are funds deducted after the request?</b>\nNO! As soon as you send the request and it is under review, the subscription is canceled, and the funds will be returned for the remaining balance on the account (the number of unused days).\n\n<b>How quickly will the funds be returned?</b>\nThe creator will return the funds 10-30 minutes (extremely rarely later) after your request in the Telegram channel specified in your profile, or will request a link to the channel from you.\n\n<b>How often can you request a refund?</b>\nNo more than once every 3 days.\n\n<b>Can I return part of the funds?</b>\nThe entire remaining balance is returned. If you need only a part, subscribe again for a different term.\n\n<b>Do you really want to request a refund?</b>",
			"Your refund request has been sent! Please wait.",
		},
		"de": {
			"<b>Wie funktioniert die Rückerstattung?</b>\nDie Rückerstattung wird in der lokalen Währung \"Stars\" verarbeitet. Die Mittel werden vom Ersteller unter dem Post in Ihrem Telegram-Kanal zurückerstattet.\n\n<b>Werden Mittel nach der Anfrage abgezogen?</b>\nNEIN! Sobald Sie die Anfrage senden und sie in Überprüfung ist, wird das Abonnement gekündigt, und die Mittel werden für den verbleibenden Saldo auf dem Konto zurückerstattet (die Anzahl der ungenutzten Tage).\n\n<b>Wie schnell werden die Mittel zurückerstattet?</b>\nDer Ersteller wird die Mittel 10-30 Minuten (extrem selten später) nach Ihrer Anfrage in dem in Ihrem Profil angegebenen Telegram-Kanal zurückerstattet, oder wird einen Link zum Kanal von Ihnen anfordern.\n\n<b>Wie oft können Sie eine Rückerstattung anfordern?</b>\nNicht mehr als einmal alle 3 Tage.\n\n<b>Kann ich einen Teil der Mittel zurückerstatten?</b>\nDer gesamte verbleibende Saldo wird zurückerstattet. Wenn Sie nur einen Teil benötigen, abonnieren Sie erneut für eine andere Laufzeit.\n\n<b>Wollen Sie wirklich eine Rückerstattung anfordern?</b>",
			"Ihre Rückerstattungsanfrage wurde gesendet! Bitte warten Sie.",
		},
		"nl": {
			"<b>Hoe werkt de restitutie?</b>\nDe restitutie wordt verwerkt in de lokale valuta \"Stars\". De fondsen worden geretourneerd door de creator onder de post in uw Telegram-kanaal.\n\n<b>Worden fondsen afgetrokken na de aanvraag?</b>\nNEE! Zodra u de aanvraag verstuurt en het in beoordeling is, wordt het abonnement geannuleerd, en de fondsen worden geretourneerd voor het resterende saldo op de account (het aantal ongebruikte dagen).\n\n<b>Hoe snel worden de fondsen geretourneerd?</b>\nDe creator zal de fondsen 10-30 minuten (extreem zelden later) na uw aanvraag in het Telegram-kanaal dat in uw profiel is gespecificeerd teruggeven, of zal een link naar het kanaal van u aanvragen.\n\n<b>Hoe vaak kunt u een restitutie aanvragen?</b>\nNiet meer dan eens elke 3 dagen.\n\n<b>Kan ik een deel van de fondsen retourneren?</b>\nHet gehele resterende saldo wordt geretourneerd. Als u alleen een deel nodig heeft, abonneer u opnieuw voor een andere termijn.\n\n<b>Wilt u echt een restitutie aanvragen?</b>",
			"Uw restitutieaanvraag is verzonden! Gelieve te wachten.",
		},
		"sv": {
			"<b>Hur fungerar återbetalningen?</b>\nÅterbetalningen behandlas i den lokala valutan \"Stars\". Pengarna kommer att returneras av skaparen under inlägget i din Telegram-kanal.\n\n<b>Drags pengar efter begäran?</b>\nNEJ! Så snart du skickar begäran och den är under granskning, avbryts prenumerationen, och pengarna returneras för det återstående saldot på kontot (antalet oanvända dagar).\n\n<b>Hur snabbt kommer pengarna att returneras?</b>\nSkaparen kommer att returnera pengarna 10-30 minuter (extremt sällan senare) efter din begäran i Telegram-kanalen som anges i din profil, eller kommer att begära en länk till kanalen från dig.\n\n<b>Hur ofta kan du begära återbetalning?</b>\nInte mer än en gång var 3:e dag.\n\n<b>Kan jag returnera en del av pengarna?</b>\nHela det återstående saldot returneras. Om du behöver bara en del, prenumerera igen för en annan period.\n\n<b>Vill du verkligen begära återbetalning?</b>",
			"Din återbetalningsbegäran har skickats! Vänligen vänta.",
		},
		"no": {
			"<b>Hvordan fungerer refusjonen?</b>\nRefusjonen behandles i den lokale valutaen \"Stars\". Midlene vil bli returnert av skaperen under innlegget i din Telegram-kanal.\n\n<b>Trekkes midler etter forespørselen?</b>\nNEI! Så snart du sender forespørselen og den er under gjennomgang, kanselleres abonnementet, og midlene vil bli returnert for den gjenværende balansen på kontoen (antall ubrukte dager).\n\n<b>Hvor raskt vil midlene bli returnert?</b>\nSkaperen vil returnere midlene 10-30 minutter (ekstremt sjelden senere) etter forespørselen din i Telegram-kanalen angitt i profilen din, eller vil be om en link til kanalen fra deg.\n\n<b>Hvor ofte kan du be om refusjon?</b>\nIkke mer enn én gang hver 3. dag.\n\n<b>Kan jeg returnere del av midlene?</b>\nHele den gjenværende balansen returneres. Hvis du trenger bare en del, abonner igjen for en annen periode.\n\n<b>Vil du virkelig be om refusjon?</b>",
			"Din refusjonsforespørsel er sendt! Vennligst vent.",
		},
		"da": {
			"<b>Hvordan fungerer refunderingen?</b>\nRefunderingen behandles i den lokale valuta \"Stars\". Pengene vil blive returneret af skaberen under posten i din Telegram-kanal.\n\n<b>Trækkes midler efter anmodningen?</b>\nNEJ! Så snart du sender anmodningen og den er under gennemgang, annulleres abonnementet, og midlene vil blive returneret for den resterende balance på kontoen (antallet af ubrugte dage).\n\n<b>Hvor hurtigt vil midlene blive returneret?</b>\nSkaberen vil returnere midlene 10-30 minutter (ekstremt sjældent senere) efter din anmodning i Telegram-kanalen angivet i din profil, eller vil anmode om et link til kanalen fra dig.\n\n<b>Hvor ofte kan du anmode om refundering?</b>\nIkke mere end én gang hver 3 dage.\n\n<b>Kan jeg returnere en del af midlene?</b>\nHele den resterende balance returneres. Hvis du kun har brug for en del, abonner igen for en anden periode.\n\n<b>Vil du virkelig anmode om refundering?</b>",
			"Din refunderingsanmodning er sendt! Venligst vent.",
		},
		"es": {
			"<b>¿Cómo funciona el reembolso?</b>\nEl reembolso se procesa en la moneda local \"Stars\". Los fondos serán devueltos por el creador bajo el post en tu canal de Telegram.\n\n<b>¿Se deducen fondos después de la solicitud?</b>\n¡NO! Tan pronto como envíes la solicitud y esté en revisión, la suscripción se cancela, y los fondos serán devueltos por el saldo restante en la cuenta (el número de días no usados).\n\n<b>¿Cuánto tiempo tardan en devolverse los fondos?</b>\nEl creador devolverá los fondos en 10-30 minutos (extremadamente raro después) después de tu solicitud en el canal de Telegram especificado en tu perfil, o solicitará un enlace al canal de ti.\n\n<b>¿Con qué frecuencia puedes solicitar un reembolso?</b>\nNo más de una vez cada 3 días.\n\n<b>¿Puedo devolver parte de los fondos?</b>\nSe devuelve todo el saldo restante. Si necesitas solo una parte, suscríbete de nuevo por un término diferente.\n\n<b>¿Realmente quieres solicitar un reembolso?</b>",
			"¡Tu solicitud de reembolso ha sido enviada! Por favor espera.",
		},
		"fr": {
			"<b>Comment fonctionne le remboursement ?</b>\nLe remboursement est traité en devise locale \"Stars\". Les fonds seront retournés par le créateur sous le post dans votre canal Telegram.\n\n<b>Les fonds sont-ils déduits après la demande ?</b>\nNON ! Dès que vous envoyez la demande et qu'elle est en examen, l'abonnement est annulé, et les fonds seront retournés pour le solde restant sur le compte (le nombre de jours non utilisés).\n\n<b>À quelle vitesse les fonds seront-ils retournés ?</b>\nLe créateur retournera les fonds 10-30 minutes (extrêmement rarement plus tard) après votre demande dans le canal Telegram indiqué dans votre profil, ou demandera un lien vers le canal de votre part.\n\n<b>À quelle fréquence pouvez-vous demander un remboursement ?</b>\nPas plus d'une fois tous les 3 jours.\n\n<b>Puis-je retourner une partie des fonds ?</b>\nL'ensemble du solde restant est retourné. Si vous avez besoin seulement d'une partie, abonnez-vous à nouveau pour un terme différent.\n\n<b>Voulez-vous vraiment demander un remboursement ?</b>",
			"Votre demande de remboursement a été envoyée ! Veuillez attendre.",
		},
		"pt": {
			"<b>Como funciona o reembolso?</b>\nO reembolso é processado na moeda local \"Stars\". Os fundos serão devolvidos pelo criador sob o post no seu canal do Telegram.\n\n<b>Os fundos são deduzidos após a solicitação?</b>\nNÃO! Assim que você envia a solicitação e ela está em revisão, a assinatura é cancelada, e os fundos serão devolvidos para o saldo restante na conta (o número de dias não usados).\n\n<b>Quão rápido os fundos serão devolvidos?</b>\nO criador devolverá os fundos 10-30 minutos (extremamente raramente mais tarde) após a sua solicitação no canal do Telegram especificado no seu perfil, ou solicitará um link para o canal de você.\n\n<b>Com que frequência você pode solicitar um reembolso?</b>\nNão mais que uma vez a cada 3 dias.\n\n<b>Posso devolver parte dos fundos?</b>\nTodo o saldo restante é devolvido. Se você precisar apenas de uma parte, assine novamente por um termo diferente.\n\n<b>Você realmente quer solicitar um reembolso?</b>",
			"Sua solicitação de reembolso foi enviada! Por favor, aguarde.",
		},
		"it": {
			"<b>Come funziona il rimborso?</b>\nIl rimborso è elaborato nella valuta locale \"Stars\". I fondi saranno restituiti dal creatore sotto il post nel tuo canale Telegram.\n\n<b>I fondi vengono dedotti dopo la richiesta?</b>\nNO! Non appena invii la richiesta e è in revisione, l'abbonamento viene annullato, e i fondi saranno restituiti per il saldo rimanente sull'account (il numero di giorni non utilizzati).\n\n<b>Quanto velocemente saranno restituiti i fondi?</b>\nIl creatore restituirà i fondi 10-30 minuti (estremamente raramente dopo) dopo la tua richiesta nel canale Telegram specificato nel tuo profilo, o richiederà un link al canale da te.\n\n<b>Quanto spesso puoi richiedere un rimborso?</b>\nNon più di una volta ogni 3 giorni.\n\n<b>Posso restituire parte dei fondi?</b>\nL'intero saldo rimanente viene restituito. Se hai bisogno solo di una parte, iscriviti di nuovo per un termine diverso.\n\n<b>Vuoi davvero richiedere un rimborso?</b>",
			"La tua richiesta di rimborso è stata inviata! Per favore attendi.",
		},
		"ru": {
			"<b>Как работает возврат средств?</b>\nВозврат средств обрабатывается в локальной валюте \"Stars\". Средства будут возвращены создателем под постом в вашем Telegram-канале.\n\n<b>Снимаются ли средства после запроса?</b>\nНЕТ! Как только вы отправите запрос и он на рассмотрении, подписка отменяется, и средства будут возвращены за оставшийся баланс на счете (количество неиспользованных дней).\n\n<b>Как быстро будут возвращены средства?</b>\nСоздатель вернет средства через 10-30 минут (крайне редко позже) после вашего запроса в Telegram-канале, указанном в вашем профиле, или запросит ссылку на канал у вас.\n\n<b>Как часто можно запрашивать возврат?</b>\nНе более одного раза каждые 3 дня.\n\n<b>Можно ли вернуть часть средств?</b>\nВозвращается весь оставшийся баланс. Если нужно только часть, подпишитесь снова на другой срок.\n\n<b>Вы действительно хотите запросить возврат?</b>",
			"Ваш запрос на возврат отправлен! Пожалуйста, подождите.",
		},
		"ua": {
			"<b>Як працює повернення коштів?</b>\nПовернення коштів обробляється в місцевій валюті \"Stars\". Кошти будуть повернені творцем під постом у вашому Telegram-каналі.\n\n<b>Чи знімаються кошти після запиту?</b>\nНІ! Як тільки ви надішлете запит і він на розгляді, підписка скасовується, і кошти будуть повернені за залишковий баланс на рахунку (кількість невикористаних днів).\n\n<b>Як швидко будуть повернені кошти?</b>\nТворець поверне кошти через 10-30 хвилин (вкрай рідко пізніше) після вашого запиту в Telegram-каналі, вказаному в вашому профілі, або запитає посилання на канал у вас.\n\n<b>Як часто можна запитувати повернення?</b>\nНе більше одного разу кожні 3 дні.\n\n<b>Чи можна повернути частину коштів?</b>\nПовертається весь залишковий баланс. Якщо потрібно тільки частина, підпишіться знову на інший термін.\n\n<b>Ви дійсно хочете запитати повернення?</b>",
			"Ваш запит на повернення надіслано! Будь ласка, зачекайте.",
		},
		"pl": {
			"<b>Jak działa zwrot pieniędzy?</b>\nZwrot jest przetwarzany w lokalnej walucie \"Stars\". Środki zostaną zwrócone przez twórcę pod postem w twoim kanale Telegram.\n\n<b>Czy środki są potrącane po żądaniu?</b>\nNIE! Jak tylko wysyłasz żądanie i jest ono w recenzji, subskrypcja jest anulowana, i środki zostaną zwrócone za pozostały balans na koncie (liczba niewykorzystanych dni).\n\n<b>Jak szybko zostaną zwrócone środki?</b>\nTwórca zwróci środki 10-30 minut (bardzo rzadko później) po twoim żądaniu w kanale Telegram określonym w twoim profilu, lub poprosi o link do kanału od ciebie.\n\n<b>Jak często możesz żądać zwrotu?</b>\nNie więcej niż raz co 3 dni.\n\n<b>Czy mogę zwrócić część środków?</b>\nCały pozostały balans jest zwracany. Jeśli potrzebujesz tylko części, zasubskrybuj ponownie na inny termin.\n\n<b>Czy naprawdę chcesz żądać zwrotu?</b>",
			"Twoje żądanie zwrotu zostało wysłane! Proszę czekać.",
		},
		"cs": {
			"<b>Jak funguje vrácení peněz?</b>\nVrácení je zpracováno v místní měně \"Stars\". Prostředky budou vráceny tvůrcem pod příspěvkem ve vašem Telegram kanálu.\n\n<b>Jsou prostředky odečteny po žádosti?</b>\nNE! Jakmile odešlete žádost a je na posouzení, předplatné je zrušeno a prostředky budou vráceny za zbývající zůstatek na účtu (počet nevyužitých dní).\n\n<b>Jak rychle budou prostředky vráceny?</b>\nTvůrce vrátí prostředky 10-30 minut (extrémně zřídka později) po vaší žádosti v Telegram kanálu uvedeném ve vašem profilu, nebo si vyžádá odkaz na kanál od vás.\n\n<b>Jak často můžete žádat o vrácení?</b>\nNe více než jednou každé 3 dny.\n\n<b>Mohu vrátit část prostředků?</b>\nVrácí se celý zbývající zůstatek. Pokud potřebujete pouze část, přihlaste se znovu na jiný termín.\n\n<b>Opravdu chcete žádat o vrácení?</b>",
			"Vaše žádost o vrácení byla odeslána! Prosím čekejte.",
		},
		"bg": {
			"<b>Как работи възстановяването?</b>\nВъзстановяването се обработва в местната валута \"Stars\". Средствата ще бъдат върнати от създателя под публикацията във вашия Telegram канал.\n\n<b>Изваждат ли се средства след заявката?</b>\nНЕ! Веднага след като изпратите заявката и тя е на преглед, абонаментът се отменя и средствата ще бъдат върнати за оставащия баланс в акаунта (броя на неизползваните дни).\n\n<b>Колко бързо ще бъдат върнати средствата?</b>\nСъздателят ще върне средствата 10-30 минути (изключително рядко по-късно) след вашата заявка в Telegram канала, посочен в профила ви, или ще поиска линк към канала от вас.\n\n<b>Колко често можете да поискате възстановяване?</b>\nНе повече от веднъж на всеки 3 дни.\n\n<b>Мога ли да върна част от средствата?</b>\nВръща се целият оставащ баланс. Ако ви трябва само част, абонирайте се отново за различен срок.\n\n<b>Наистина ли искате да поискате възстановяване?</b>",
			"Вашата заявка за възстановяване е изпратена! Моля, изчакайте.",
		},
		"sr": {
			"<b>Kako funkcioniše povraćaj novca?</b>\nPovraćaj se obrađuje u lokalnoj valuti \"Stars\". Sredstva će biti vraćena od strane kreatora ispod posta u vašem Telegram kanalu.\n\n<b>Da li se sredstva oduzimaju nakon zahteva?</b>\nNE! Čim pošaljete zahtev i on je na pregledu, pretplata se otkazuje, i sredstva će biti vraćena za preostali saldo na računu (broj nekorišćenih dana).\n\n<b>Koliko brzo će sredstva biti vraćena?</b>\nKreator će vratiti sredstva 10-30 minuta (izuzetno retko kasnije) nakon vašeg zahteva u Telegram kanalu navedenom u vašem profilu, ili će zatražiti link ka kanalu od vas.\n\n<b>Koliko često možete zahtevati povraćaj?</b>\nNe više od jednom svaka 3 dana.\n\n<b>Mogu li vratiti deo sredstava?</b>\nVraća se ceo preostali saldo. Ako vam treba samo deo, pretplatite se ponovo za drugačiji period.\n\n<b>Da li stvarno želite da zahtevate povraćaj?</b>",
			"Vaš zahtev za povraćaj je poslat! Molimo sačekajte.",
		},
		"hr": {
			"<b>Kako funkcionira povrat novca?</b>\nPovrat se obrađuje u lokalnoj valuti \"Stars\". Sredstva će biti vraćena od strane stvoritelja ispod objave u vašem Telegram kanalu.\n\n<b>Jesu li sredstva odbijena nakon zahtjeva?</b>\nNE! Čim pošaljete zahtjev i on je na pregledu, pretplata se otkazuje, i sredstva će biti vraćena za preostali saldo na računu (broj neiskorištenih dana).\n\n<b>Koliko brzo će sredstva biti vraćena?</b>\nStvoritelj će vratiti sredstva 10-30 minuta (izuzetno rijetko kasnije) nakon vašeg zahtjeva u Telegram kanalu navedenom u vašem profilu, ili će zatražiti poveznicu na kanal od vas.\n\n<b>Koliko često možete zatražiti povrat?</b>\nNe više od jednom svaka 3 dana.\n\n<b>Mogu li vratiti dio sredstava?</b>\nVraća se cijeli preostali saldo. Ako trebate samo dio, pretplatite se ponovno za drugačiji rok.\n\n<b>Želite li stvarno zatražiti povrat?</b>",
			"Vaš zahtjev za povrat je poslan! Molimo pričekajte.",
		},
		"sk": {
			"<b>Ako funguje vrátenie peňazí?</b>\nVrátenie je spracované v lokálnej mene \"Stars\". Prostriedky budú vrátené tvorcom pod príspevkom vo vašom Telegram kanáli.\n\n<b>Sú prostriedky odpočítané po žiadosti?</b>\nNIE! Hneď ako odošlete žiadosť a je na posúdení, predplatné je zrušené a prostriedky budú vrátené za zostávajúci zostatok na účte (počet nevyužitých dní).\n\n<b>Ako rýchlo budú prostriedky vrátené?</b>\nTvorca vráti prostriedky 10-30 minút (extrémne zriedka neskôr) po vašej žiadosti v Telegram kanáli uvedenom vo vašom profile, alebo si vyžiada link na kanál od vás.\n\n<b>Ako často môžete žiadať o vrátenie?</b>\nNie viac ako raz každé 3 dni.\n\n<b>Môžem vrátiť časť prostriedkov?</b>\nVracia sa celý zostávajúci zostatok. Ak potrebujete len časť, predplaťte sa znova na iný termín.\n\n<b>Naozaj chcete žiadať o vrátenie?</b>",
			"Vaša žiadosť o vrátenie bola odoslaná! Prosím čakajte.",
		},
		"sl": {
			"<b>Kako deluje vračilo?</b>\nVračilo se obdela v lokalni valuti \"Stars\". Sredstva bodo vrnjena s strani ustvarjalca pod objavo v vašem Telegram kanalu.\n\n<b>Ali se sredstva odštejejo po zahtevi?</b>\nNE! Takoj ko pošljete zahtevo in je na pregled, se naročnina prekine, in sredstva bodo vrnjena za preostali saldo na računu (število neuporabljenih dni).\n\n<b>Kako hitro bodo sredstva vrnjena?</b>\nUstvarjalec bo vrnil sredstva 10-30 minut (izjemno redko kasneje) po vaši zahtevi v Telegram kanalu, navedenem v vašem profilu, ali bo zahteval povezavo do kanala od vas.\n\n<b>Kako pogosto lahko zahtevate vračilo?</b>\nNe več kot enkrat vsakih 3 dni.\n\n<b>Ali lahko vrnem del sredstev?</b>\nVrne se celoten preostali saldo. Če potrebujete samo del, se naročite ponovno za drugačen rok.\n\n<b>Ali res želite zahtevati vračilo?</b>",
			"Vaša zahteva za vračilo je bila poslana! Prosimo počakajte.",
		},
		"lt": {
			"<b>Kaip veikia grąžinimas?</b>\nGrąžinimas apdorojamas vietine valiuta \"Stars\". Lėšos bus grąžintos kūrėjo po įrašu jūsų Telegram kanale.\n\n<b>Ar lėšos nuskaičiuojamos po prašymo?</b>\nNE! Vos tik išsiunčiate prašymą ir jis peržiūrimas, prenumerata atšaukiama, ir lėšos bus grąžintos už likusį balansą sąskaitoje (nenaudotų dienų skaičius).\n\n<b>Kaip greitai bus grąžintos lėšos?</b>\nKūrėjas grąžins lėšas 10-30 minučių (ypač retai vėliau) po jūsų prašymo Telegram kanale, nurodytame jūsų profilyje, arba paprašys nuorodos į kanalą iš jūsų.\n\n<b>Kaip dažnai galite prašyti grąžinimo?</b>\nNe dažniau kaip kartą kas 3 dienas.\n\n<b>Ar galiu grąžinti dalį lėšų?</b>\nGrąžinamas visas likęs balansas. Jei reikia tik dalies, prenumeruokite vėl kitam terminui.\n\n<b>Ar tikrai norite prašyti grąžinimo?</b>",
			"Jūsų grąžinimo prašymas išsiųstas! Prašome palaukti.",
		},
		"lv": {
			"<b>Kā darbojas atmaksa?</b>\nAtmaksa tiek apstrādāta vietējā valūtā \"Stars\". Līdzekļi tiks atgriezti no radītāja zem ieraksta jūsu Telegram kanālā.\n\n<b>Vai līdzekļi tiek atskaitīti pēc pieprasījuma?</b>\nNĒ! Tiklīdz jūs nosūtāt pieprasījumu un tas ir pārskatīšanā, abonements tiek atcelts, un līdzekļi tiks atgriezti par atlikušo bilanci kontā (neizmantoto dienu skaits).\n\n<b>Cik ātri līdzekļi tiks atgriezti?</b>\nRadītājs atgriezīs līdzekļus 10-30 minūtes (ļoti reti vēlāk) pēc jūsu pieprasījuma Telegram kanālā, kas norādīts jūsu profilā, vai pieprasīs saiti uz kanālu no jums.\n\n<b>Cik bieži jūs varat pieprasīt atmaksu?</b>\nNe vairāk kā reizi ik pēc 3 dienām.\n\n<b>Vai es varu atgriezt daļu līdzekļu?</b>\nTiek atgriezta visa atlikusī bilance. Ja jums vajag tikai daļu, abonējiet atkal citam termiņam.\n\n<b>Vai jūs tiešām vēlaties pieprasīt atmaksu?</b>",
			"Jūsu atmaksas pieprasījums ir nosūtīts! Lūdzu uzgaidiet.",
		},
		"et": {
			"<b>Kuidas tagastus töötab?</b>\nTagastus töödeldakse kohalikus valuutas \"Stars\". Vahendid tagastatakse looja poolt postituse all teie Telegrami kanalis.\n\n<b>Kas vahendid võetakse maha pärast taotlust?</b>\nEI! Niipea kui saadate taotluse ja see on ülevaatamisel, tühistatakse tellimus ja vahendid tagastatakse konto jäägile (kasutamata päevade arv).\n\n<b>Kui kiiresti vahendid tagastatakse?</b>\nLooja tagastab vahendid 10-30 minuti jooksul (äärmiselt harva hiljem) pärast teie taotlust teie profiilis määratud Telegrami kanalis või küsib teilt kanali linki.\n\n<b>Kui tihti saate tagastust taotleda?</b>\nMitte rohkem kui üks kord iga 3 päeva järel.\n\n<b>Kas ma saan tagastada osa vahenditest?</b>\nTagastatakse kogu jääk. Kui vajate ainult osa, tellige uuesti teistsuguse perioodiga.\n\n<b>Kas te tõesti soovite tagastust taotleda?</b>",
			"Teie tagastustaotlus on saadetud! Palun oodake.",
		},
		"fi": {
			"<b>Miten palautus toimii?</b>\nPalautus käsitellään paikallisessa valuutassa \"Stars\". Varat palautetaan luojan toimesta postauksen alla Telegram-kanavallasi.\n\n<b>Vähennetäänkö varoja pyynnön jälkeen?</b>\nEI! Heti kun lähetät pyynnön ja se on tarkistuksessa, tilaus peruutetaan, ja varat palautetaan tilin jäljellä olevalle saldolle (käyttämättömien päivien määrä).\n\n<b>Kuinka nopeasti varat palautetaan?</b>\nLuoja palauttaa varat 10-30 minuutin kuluessa (erittäin harvoin myöhemmin) pyyntösi jälkeen profiilissasi määritetyssä Telegram-kanavassa tai pyytää linkkiä kanavaan sinulta.\n\n<b>Kuinka usein voit pyytää palautusta?</b>\nEnintään kerran joka 3. päivä.\n\n<b>Voinko palauttaa osan varoista?</b>\nKoko jäljellä oleva saldo palautetaan. Jos tarvitset vain osan, tilaa uudelleen eri ajanjaksolla.\n\n<b>Haluatko todella pyytää palautusta?</b>",
			"Palautuspyyntösi on lähetetty! Odota.",
		},
		"el": {
			"<b>Πώς λειτουργεί η επιστροφή χρημάτων;</b>\nΗ επιστροφή επεξεργάζεται στο τοπικό νόμισμα \"Stars\". Τα κεφάλαια θα επιστραφούν από τον δημιουργό κάτω από την ανάρτηση στο κανάλι σας στο Telegram.\n\n<b>Αφαιρούνται κεφάλαια μετά το αίτημα;</b>\nΟΧΙ! Μόλις στείλετε το αίτημα και είναι υπό εξέταση, η συνδρομή ακυρώνεται και τα κεφάλαια θα επιστραφούν για το υπόλοιπο υπόλοιπο στον λογαριασμό (ο αριθμός των αχρησιμοποίητων ημερών).\n\n<b>Πόσο γρήγορα θα επιστραφούν τα κεφάλαια;</b>\nΟ δημιουργός θα επιστρέψει τα κεφάλαια 10-30 λεπτά (εξαιρετικά σπάνια αργότερα) μετά το αίτημά σας στο κανάλι Telegram που καθορίζεται στο προφίλ σας, ή θα ζητήσει σύνδεσμο στο κανάλι από εσάς.\n\n<b>Πόσο συχνά μπορείτε να ζητήσετε επιστροφή;</b>\nΌχι περισσότερο από μία φορά κάθε 3 ημέρες.\n\n<b>Μπορώ να επιστρέψω μέρος των κεφαλαίων;</b>\nΕπιστρέφεται ολόκληρο το υπόλοιπο υπόλοιπο. Αν χρειάζεστε μόνο μέρος, εγγραφείτε ξανά για διαφορετική διάρκεια.\n\n<b>Θέλετε πραγματικά να ζητήσετε επιστροφή;</b>",
			"Το αίτημα επιστροφής σας έχει σταλεί! Παρακαλώ περιμένετε.",
		},
		"ro": {
			"<b>Cum funcționează rambursarea?</b>\nRambursarea este procesată în moneda locală \"Stars\". Fondurile vor fi returnate de creator sub postarea din canalul tău Telegram.\n\n<b>Sunt fondurile deduse după cerere?</b>\nNU! De îndată ce trimiteți cererea și este în revizuire, abonamentul este anulat, și fondurile vor fi returnate pentru soldul rămas în cont (numărul de zile neutilizate).\n\n<b>Cât de repede vor fi returnate fondurile?</b>\nCreatorul va returna fondurile în 10-30 de minute (extrem de rar mai târziu) după cererea dvs. în canalul Telegram specificat în profilul dvs., sau va solicita un link către canal de la dvs.\n\n<b>Cât de des puteți cere rambursare?</b>\nNu mai mult de o dată la fiecare 3 zile.\n\n<b>Pot returna o parte din fonduri?</b>\nSe returnează întregul sold rămas. Dacă aveți nevoie doar de o parte, abonați-vă din nou pentru un termen diferit.\n\n<b>Doriți cu adevărat să cereți rambursare?</b>",
			"Cererea dvs. de rambursare a fost trimisă! Vă rugăm să așteptați.",
		},
		"hu": {
			"<b>Hogyan működik a visszatérítés?</b>\nA visszatérítés a helyi pénznemben \"Stars\" történik. Az alapokat a létrehozó adja vissza a bejegyzés alatt a Telegram csatornádon.\n\n<b>Levonódnak az alapok a kérés után?</b>\nNEM! Amint elküldi a kérést és az felülvizsgálat alatt áll, az előfizetés megszűnik, és az alapok visszatérítésre kerülnek a számlán maradt egyenlegért (a fel nem használt napok száma).\n\n<b>Milyen gyorsan térítik vissza az alapokat?</b>\nA létrehozó 10-30 percen belül (rendkívül ritkán később) visszatéríti az alapokat a kérését követően a profiljában megadott Telegram csatornán, vagy kéri a csatorna linkjét Öntől.\n\n<b>Milyen gyakran kérhet visszatérítést?</b>\nNem több mint egyszer 3 naponta.\n\n<b>Visszatéríthetek részét az alapoknak?</b>\nA teljes maradt egyenleg térül vissza. Ha csak részre van szüksége, iratkozzon fel újra más időtartamra.\n\n<b>Tényleg kérni szeretné a visszatérítést?</b>",
			"A visszatérítési kérelme elküldve! Kérem várjon.",
		},
		"ar": {
			"<b>كيف يعمل الاسترداد؟</b>\nيتم معالجة الاسترداد في العملة المحلية \"Stars\". سيتم إعادة الأموال من قبل المنشئ تحت المنشور في قناتك على Telegram.\n\n<b>هل يتم خصم الأموال بعد الطلب؟</b>\nلا! بمجرد إرسال الطلب وهو قيد المراجعة، يتم إلغاء الاشتراك، وسيتم إعادة الأموال للرصيد المتبقي على الحساب (عدد الأيام غير المستخدمة).\n\n<b>كم من الوقت يستغرق إعادة الأموال؟</b>\nسيقوم المنشئ بإعادة الأموال خلال 10-30 دقيقة (نادرًا جدًا بعد ذلك) بعد طلبك في قناة Telegram المحددة في ملفك الشخصي، أو سيطلب رابط القناة منك.\n\n<b>كم مرة يمكنك طلب الاسترداد؟</b>\nلا أكثر من مرة واحدة كل 3 أيام.\n\n<b>هل يمكنني إعادة جزء من الأموال؟</b>\nيتم إعادة الرصيد المتبقي بأكمله. إذا كنت بحاجة إلى جزء فقط، اشترك مرة أخرى لمدة مختلفة.\n\n<b>هل تريد حقًا طلب الاسترداد؟</b>",
			"تم إرسال طلب الاسترداد الخاص بك! يرجى الانتظار.",
		},
		"fa": {
			"<b>بازپرداخت چگونه کار می‌کند؟</b>\nبازپرداخت در ارز محلی \"Stars\" پردازش می‌شود. وجوه توسط سازنده زیر پست در کانال تلگرام شما بازگردانده می‌شود.\n\n<b>آیا وجوه پس از درخواست کسر می‌شوند؟</b>\nخیر! به محض ارسال درخواست و بررسی آن، اشتراک لغو می‌شود و وجوه برای موجودی باقی‌مانده در حساب (تعداد روزهای استفاده نشده) بازگردانده می‌شود.\n\n<b>وجوه چقدر سریع بازگردانده می‌شوند؟</b>\nسازنده وجوه را 10-30 دقیقه (به ندرت دیرتر) پس از درخواست شما در کانال تلگرام مشخص شده در پروفایل شما باز می‌گرداند، یا لینک کانال را از شما درخواست می‌کند.\n\n<b>چقدر اغلب می‌توانید درخواست بازپرداخت کنید؟</b>\nبیش از یک بار هر 3 روز نه.\n\n<b>آیا می‌توانم بخشی از وجوه را بازگردانم؟</b>\nکل موجودی باقی‌مانده بازگردانده می‌شود. اگر فقط بخشی نیاز دارید، دوباره برای مدت متفاوت مشترک شوید.\n\n<b>آیا واقعاً می‌خواهید درخواست بازپرداخت کنید؟</b>",
			"درخواست بازپرداخت شما ارسال شد! لطفاً صبر کنید.",
		},
		"tr": {
			"<b>İade nasıl çalışır?</b>\nİade yerel para birimi \"Stars\" ile işlenir. Fonlar, yaratıcı tarafından Telegram kanalınızdaki yayın altında iade edilir.\n\n<b>İstekten sonra fonlar kesilir mi?</b>\nHAYIR! Talebi gönderdiğiniz anda ve incelenirken, abonelik iptal edilir ve hesapta kalan bakiye için fonlar iade edilir (kullanılmayan gün sayısı).\n\n<b>Fonlar ne kadar hızlı iade edilir?</b>\nYaratıcı, talebinizden sonra 10-30 dakika (son derece nadir olarak daha sonra) profilinizde belirtilen Telegram kanalında fonları iade eder veya sizden kanal bağlantısını ister.\n\n<b>İade talebini ne sıklıkta yapabilirsiniz?</b>\nHer 3 günde bir defadan fazla değil.\n\n<b>Fonların bir kısmını iade edebilir miyim?</b>\nTüm kalan bakiye iade edilir. Yalnızca bir kısmına ihtiyacınız varsa, farklı bir süre için yeniden abone olun.\n\n<b>Gerçekten iade talep etmek istiyor musunuz?</b>",
			"İade talebiniz gönderildi! Lütfen bekleyin.",
		},
		"he": {
			"<b>איך עובד ההחזר?</b>\nההחזר מעובד במטבע המקומי \"Stars\". הכספים יוחזרו על ידי היוצר מתחת לפוסט בערוץ הטלגרם שלך.\n\n<b>האם כספים מנוכים לאחר הבקשה?</b>\nלא! ברגע שתשלח את הבקשה והיא בבדיקה, המנוי מבוטל, והכספים יוחזרו עבור היתרה הנותרת בחשבון (מספר הימים שלא נוצלו).\n\n<b>כמה מהר יוחזרו הכספים?</b>\nהיוצר יחזיר את הכספים 10-30 דקות (מאוד נדיר מאוחר יותר) לאחר בקשתך בערוץ הטלגרם שצוין בפרופיל שלך, או יבקש קישור לערוץ ממך.\n\n<b>באיזו תדירות ניתן לבקש החזר?</b>\nלא יותר מפעם אחת כל 3 ימים.\n\n<b>האם ניתן להחזיר חלק מהכספים?</b>\nכל היתרה הנותרת מוחזרת. אם אתה צריך רק חלק, הרשם שוב לתקופה שונה.\n\n<b>האם אתה באמת רוצה לבקש החזר?</b>",
			"בקשת ההחזר שלך נשלחה! אנא המתן.",
		},
		"zh": {
			"<b>退款如何运作？</b>\n退款以本地货币 \"Stars\" 处理。资金将由创建者在您的 Telegram 频道中的帖子下返回。\n\n<b>请求后是否扣除资金？</b>\n不！一旦您发送请求并处于审查中，订阅将被取消，资金将返回账户上剩余余额（未使用天数）。\n\n<b>资金将多快返回？</b>\n创建者将在您的请求后 10-30 分钟（极少情况下更晚）在您的个人资料中指定的 Telegram 频道中返回资金，或向您请求频道链接。\n\n<b>您可以多经常请求退款？</b>\n每 3 天不超过一次。\n\n<b>我可以返回部分资金吗？</b>\n返回整个剩余余额。如果您只需一部分，请再次订阅不同的期限。\n\n<b>您真的想请求退款吗？</b>",
			"您的退款请求已发送！请等待。",
		},
		"ja": {
			"<b>払い戻しはどう機能しますか？</b>\n払い戻しは現地通貨 \"Stars\" で処理されます。資金は作成者によってあなたの Telegram チャンネルの投稿の下で返金されます。\n\n<b>リクエスト後に資金が差し引かれますか？</b>\nいいえ！リクエストを送信し、それが審査中になると、サブスクリプションがキャンセルされ、アカウントの残高（未使用の日数）に対して資金が返金されます。\n\n<b>資金はどれくらい早く返金されますか？</b>\n作成者はリクエスト後 10-30 分（極めて稀にそれ以降）以内にプロフィールで指定された Telegram チャンネルで資金を返金するか、チャンネルのリンクをあなたにリクエストします。\n\n<b>払い戻しをどれくらいの頻度でリクエストできますか？</b>\n3 日に 1 回を超えない。\n\n<b>資金の一部を返金できますか？</b>\n残りの残高全体が返金されます。一部のみが必要な場合は、異なる期間で再度サブスクライブしてください。\n\n<b>本当に払い戻しをリクエストしますか？</b>",
			"払い戻しリクエストが送信されました！お待ちください。",
		},
		"ko": {
			"<b>환불은 어떻게 작동하나요?</b>\n환불은 현지 통화 \"Stars\"로 처리됩니다. 자금은 제작자가 귀하의 Telegram 채널 게시물 아래에서 반환합니다.\n\n<b>요청 후 자금이 차감되나요?</b>\n아니요! 요청을 보내고 검토 중인 즉시 구독이 취소되며, 계정의 잔여 잔액(사용하지 않은 일수)에 대해 자금이 반환됩니다.\n\n<b>자금이 얼마나 빨리 반환되나요?</b>\n제작자는 요청 후 10-30분(극히 드물게 그 이후) 이내에 프로필에 지정된 Telegram 채널에서 자금을 반환하거나, 채널 링크를 요청합니다.\n\n<b>환불을 얼마나 자주 요청할 수 있나요?</b>\n3일에 한 번 이상 불가.\n\n<b>자금의 일부를 반환할 수 있나요?</b>\n전체 잔여 잔액이 반환됩니다. 일부만 필요하다면 다른 기간으로 다시 구독하세요.\n\n<b>정말 환불을 요청하시겠습니까?</b>",
			"환불 요청이 전송되었습니다! 기다려 주세요.",
		},
		"vi": {
			"<b>Hoàn tiền hoạt động như thế nào?</b>\nHoàn tiền được xử lý bằng tiền tệ địa phương \"Stars\". Số tiền sẽ được trả lại bởi người tạo dưới bài đăng trong kênh Telegram của bạn.\n\n<b>Số tiền có bị trừ sau yêu cầu không?</b>\nKHÔNG! Ngay khi bạn gửi yêu cầu và nó đang được xem xét, đăng ký bị hủy, và số tiền sẽ được trả lại cho số dư còn lại trên tài khoản (số ngày chưa sử dụng).\n\n<b>Số tiền sẽ được trả lại nhanh như thế nào?</b>\nNgười tạo sẽ trả lại số tiền 10-30 phút (cực kỳ hiếm muộn hơn) sau yêu cầu của bạn trong kênh Telegram được chỉ định trong hồ sơ của bạn, hoặc sẽ yêu cầu liên kết đến kênh từ bạn.\n\n<b>Bạn có thể yêu cầu hoàn tiền bao lâu một lần?</b>\nKhông quá một lần mỗi 3 ngày.\n\n<b>Tôi có thể trả lại một phần số tiền không?</b>\nToàn bộ số dư còn lại được trả lại. Nếu bạn chỉ cần một phần, hãy đăng ký lại cho một kỳ hạn khác.\n\n<b>Bạn có thực sự muốn yêu cầu hoàn tiền không?</b>",
			"Yêu cầu hoàn tiền của bạn đã được gửi! Vui lòng chờ.",
		},
		"th": {
			"<b>การคืนเงินทำงานอย่างไร?</b>\nการคืนเงินถูกประมวลผลในสกุลเงินท้องถิ่น \"Stars\". เงินจะถูกคืนโดยผู้สร้างใต้โพสต์ในช่อง Telegram ของคุณ.\n\n<b>เงินถูกหักหลังจากคำขอหรือไม่?</b>\nไม่! ทันทีที่คุณส่งคำขอและอยู่ระหว่างการตรวจสอบ การสมัครสมาชิกจะถูกยกเลิก และเงินจะถูกคืนสำหรับยอดคงเหลือที่เหลือในบัญชี (จำนวนวันที่ไม่ได้ใช้).\n\n<b>เงินจะถูกคืนเร็วแค่ไหน?</b>\nผู้สร้างจะคืนเงิน 10-30 นาที (หายากมากที่จะช้ากว่า) หลังจากคำขอของคุณในช่อง Telegram ที่ระบุในโปรไฟล์ของคุณ หรือจะขอ链接ช่องจากคุณ.\n\n<b>คุณสามารถขอคืนเงินได้บ่อยแค่ไหน?</b>\nไม่เกินหนึ่งครั้งทุก 3 วัน.\n\n<b>ฉันสามารถคืนเงินบางส่วนได้หรือไม่?</b>\nคืนยอดคงเหลือทั้งหมดที่เหลือ ถ้าต้องการเพียงบางส่วน สมัครสมาชิกอีกครั้งสำหรับระยะเวลาอื่น.\n\n<b>คุณต้องการขอคืนเงินจริงๆ หรือไม่?</b>",
			"คำขอคืนเงินของคุณถูกส่งแล้ว! โปรดรอ.",
		},
		"id": {
			"<b>Bagaimana pengembalian dana bekerja?</b>\nPengembalian dana diproses dalam mata uang lokal \"Stars\". Dana akan dikembalikan oleh pembuat di bawah posting di saluran Telegram Anda.\n\n<b>Apakah dana dipotong setelah permintaan?</b>\nTIDAK! Segera setelah Anda mengirim permintaan dan sedang ditinjau, langganan dibatalkan, dan dana akan dikembalikan untuk saldo yang tersisa di akun (jumlah hari yang tidak digunakan).\n\n<b>Seberapa cepat dana akan dikembalikan?</b>\nPembuat akan mengembalikan dana 10-30 menit (sangat jarang lebih lambat) setelah permintaan Anda di saluran Telegram yang ditentukan di profil Anda, atau akan meminta tautan ke saluran dari Anda.\n\n<b>Seberapa sering Anda bisa meminta pengembalian dana?</b>\nTidak lebih dari sekali setiap 3 hari.\n\n<b>Dapatkah saya mengembalikan sebagian dana?</b>\nSeluruh saldo yang tersisa dikembalikan. Jika Anda hanya membutuhkan sebagian, berlangganan lagi untuk jangka waktu yang berbeda.\n\n<b>Apakah Anda benar-benar ingin meminta pengembalian dana?</b>",
			"Permintaan pengembalian dana Anda telah dikirim! Silakan tunggu.",
		},
		"ms": {
			"<b>Bagaimana bayaran balik berfungsi?</b>\nBayaran balik diproses dalam mata wang tempatan \"Stars\". Dana akan dikembalikan oleh pencipta di bawah siaran di saluran Telegram anda.\n\n<b>Adakah dana ditolak selepas permintaan?</b>\nTIDAK! Sebaik sahaja anda menghantar permintaan dan ia sedang disemak, langganan dibatalkan, dan dana akan dikembalikan untuk baki baki dalam akaun (bilangan hari yang tidak digunakan).\n\n<b>Berapa cepat dana akan dikembalikan?</b>\nPencipta akan mengembalikan dana 10-30 minit (sangat jarang lewat) selepas permintaan anda di saluran Telegram yang ditentukan dalam profil anda, atau akan meminta pautan ke saluran daripada anda.\n\n<b>Berapa kerap anda boleh meminta bayaran balik?</b>\nTidak lebih daripada sekali setiap 3 hari.\n\n<b>Bolehkah saya mengembalikan sebahagian dana?</b>\nKeseluruhan baki baki dikembalikan. Jika anda memerlukan hanya sebahagian, langgan semula untuk tempoh yang berbeza.\n\n<b>Adakah anda benar-benar mahu meminta bayaran balik?</b>",
			"Permintaan bayaran balik anda telah dihantar! Sila tunggu.",
		},
		"tl": {
			"<b>Paano gumagana ang refund?</b>\nAng refund ay pinoproseso sa lokal na pera \"Stars\". Ang pondo ay ibabalik ng creator sa ilalim ng post sa iyong Telegram channel.\n\n<b>May binabawas bang pondo pagkatapos ng request?</b>\nHINDI! Sa sandaling ipadala mo ang request at ito ay nasa review, ang subscription ay kinakansela, at ang pondo ay ibabalik para sa natitirang balanse sa account (bilang ng hindi nagamit na araw).\n\n<b>Gaano kabilis ibabalik ang pondo?</b>\nIbabalik ng creator ang pondo 10-30 minuto (lubhang bihira mamaya) pagkatapos ng iyong request sa Telegram channel na tinukoy sa iyong profile, o hihingi ng link sa channel mula sa iyo.\n\n<b>Gaano kadalas maaari kang mag-request ng refund?</b>\nHindi higit sa isang beses bawat 3 araw.\n\n<b>Maaari ba akong magbalik ng bahagi ng pondo?</b>\nIbabalik ang buong natitirang balanse. Kung kailangan mo lamang ng bahagi, mag-subscribe muli para sa ibang termino.\n\n<b>Talaga bang gusto mong mag-request ng refund?</b>",
			"Naipadala na ang iyong request para sa refund! Mangyaring maghintay.",
		},
		"hi": {
			"<b>रिफंड कैसे काम करता है?</b>\nरिफंड स्थानीय मुद्रा \"Stars\" में संसाधित किया जाता है। धनराशि क्रिएटर द्वारा आपके Telegram चैनल में पोस्ट के नीचे वापस की जाएगी।\n\n<b>अनुरोध के बाद धन काटा जाता है?</b>\nनहीं! जैसे ही आप अनुरोध भेजते हैं और यह समीक्षा में है, सदस्यता रद्द कर दी जाती है, और खाते पर शेष बैलेंस (अप्रयुक्त दिनों की संख्या) के लिए धन वापस कर दिया जाएगा।\n\n<b>धन कितनी जल्दी वापस किया जाएगा?</b>\nक्रिएटर अनुरोध के बाद 10-30 मिनट (अत्यंत दुर्लभ रूप से बाद में) आपके प्रोफाइल में निर्दिष्ट Telegram चैनल में धन वापस करेगा, या आपसे चैनल का लिंक मांगेगा।\n\n<b>आप कितनी बार रिफंड का अनुरोध कर सकते हैं?</b>\nहर 3 दिनों में एक बार से अधिक नहीं।\n\n<b>क्या मैं धन का हिस्सा वापस कर सकता हूं?</b>\nपूरा शेष बैलेंस वापस किया जाता है। यदि आपको केवल हिस्सा चाहिए, तो अलग अवधि के लिए फिर से सब्सक्राइब करें।\n\n<b>क्या आप वाकई रिफंड का अनुरोध करना चाहते हैं?</b>",
			"आपका रिफंड अनुरोध भेज दिया गया है! कृपया प्रतीक्षा करें।",
		},
		"ur": {
			"<b>ریفنڈ کیسے کام کرتا ہے؟</b>\nریفنڈ مقامی کرنسی \"Stars\" میں پروسیس کیا جاتا ہے۔ فنڈز تخلیق کار کی طرف سے آپ کے ٹیلی گرام چینل میں پوسٹ کے نیچے واپس کیے جائیں گے۔\n\n<b>درخواست کے بعد فنڈز کاٹے جاتے ہیں؟</b>\nنہیں! جیسے ہی آپ درخواست بھیجیں اور یہ جائزے میں ہو، سبسکرپشن منسوخ ہو جاتی ہے، اور اکاؤنٹ پر باقی بیلنس (غیر استعمال شدہ دنوں کی تعداد) کے لیے فنڈز واپس کر دیے جائیں گے۔\n\n<b>فنڈز کتنی جلدی واپس کیے جائیں گے؟</b>\nتخلیق کار درخواست کے بعد 10-30 منٹ (انتہائی نایاب طور پر بعد میں) آپ کے پروفائل میں مخصوص ٹیلی گرام چینل میں فنڈز واپس کرے گا، یا آپ سے چینل کا لنک مانگے گا۔\n\n<b>آپ کتنی بار ریفنڈ کی درخواست کر سکتے ہیں؟</b>\nہر 3 دن میں ایک بار سے زیادہ نہیں۔\n\n<b>کیا میں فنڈز کا حصہ واپس کر سکتا ہوں؟</b>\nپورا باقی بیلنس واپس کیا جاتا ہے۔ اگر آپ کو صرف حصہ چاہیے تو مختلف مدت کے لیے دوبارہ سبسکرائب کریں۔\n\n<b>کیا آپ واقعی ریفنڈ کی درخواست کرنا چاہتے ہیں؟</b>",
			"آپ کی ریفنڈ کی درخواست بھیج دی گئی ہے! براہ مہربانی انتظار کریں۔",
		},
		"bn": {
			"<b>রিফান্ড কীভাবে কাজ করে?</b>\nরিফান্ড স্থানীয় মুদ্রা \"Stars\"-এ প্রক্রিয়া করা হয়। তহবিলগুলি নির্মাতা দ্বারা আপনার Telegram চ্যানেলে পোস্টের নীচে ফেরত দেওয়া হবে।\n\n<b>অনুরোধের পর তহবিল কাটা হয়?</b>\nনা! আপনি অনুরোধ পাঠানোর সাথে সাথে এবং এটি পর্যালোচনায় থাকলে, সাবস্ক্রিপশন বাতিল করা হয়, এবং অ্যাকাউন্টে অবশিষ্ট ব্যালেন্সের জন্য তহবিল ফেরত দেওয়া হবে (অব্যবহৃত দিনের সংখ্যা)।\n\n<b>তহবিল কত তাড়াতাড়ি ফেরত দেওয়া হবে?</b>\nনির্মাতা আপনার অনুরোধের পর 10-30 মিনিট (অত্যন্ত কদাচিৎ পরে) আপনার প্রোফাইলে নির্দিষ্ট Telegram চ্যানেলে তহবিল ফেরত দেবেন, অথবা আপনার কাছ থেকে চ্যানেলের লিঙ্ক চাইবেন।\n\n<b>আপনি কতবার রিফান্ড অনুরোধ করতে পারেন?</b>\nপ্রতি 3 দিনে একবারের বেশি না।\n\n<b>আমি তহবিলের অংশ ফেরত দিতে পারি?</b>\nসম্পূর্ণ অবশিষ্ট ব্যালেন্স ফেরত দেওয়া হয়। যদি আপনার শুধুমাত্র অংশ দরকার হয়, তাহলে ভিন্ন মেয়াদের জন্য আবার সাবস্ক্রাইব করুন।\n\n<b>আপনি কি সত্যিই রিফান্ড অনুরোধ করতে চান?</b>",
			"আপনার রিফান্ড অনুরোধ পাঠানো হয়েছে! অনুগ্রহ করে অপেক্ষা করুন।",
		},
		"ta": {
			"<b>பணத்திருப்பி எப்படி வேலை செய்கிறது?</b>\nபணத்திருப்பி உள்ளூர் நாணயம் \"Stars\" இல் செயல்படுத்தப்படுகிறது. நிதிகள் உருவாக்கியவரால் உங்கள் Telegram சேனலில் பதிவின் கீழ் திருப்பி அளிக்கப்படும்.\n\n<b>கோரிக்கைக்குப் பிறகு நிதிகள் கழிக்கப்படுமா?</b>\nஇல்லை! நீங்கள் கோரிக்கையை அனுப்பியவுடன் அது ஆய்வில் இருக்கும் போது, சந்தா ரத்து செய்யப்படும், மற்றும் கணக்கில் இருக்கும் மீதி இருப்புக்கு நிதிகள் திருப்பி அளிக்கப்படும் (பயன்படுத்தப்படாத நாட்களின் எண்ணிக்கை).\n\n<b>நிதிகள் எவ்வளவு விரைவில் திருப்பி அளிக்கப்படும்?</b>\nஉருவாக்கியவர் உங்கள் கோரிக்கைக்குப் பிறகு 10-30 நிமிடங்கள் (மிகவும் அரிதாக பிறகு) உங்கள் சுயவிவரத்தில் குறிப்பிடப்பட்ட Telegram சேனலில் நிதிகளை திருப்பி அளிப்பார், அல்லது உங்களிடமிருந்து சேனல் இணைப்பை கோருவார்.\n\n<b>நீங்கள் எவ்வளவு அடிக்கடி பணத்திருப்பி கோரலாம்?</b>\n3 நாட்களுக்கு ஒரு முறைக்கு மேல் இல்லை.\n\n<b>நான் நிதிகளின் ஒரு பகுதியை திருப்பி அளிக்கலாமா?</b>\nமுழு மீதி இருப்பு திருப்பி அளிக்கப்படும். உங்களுக்கு ஒரு பகுதி மட்டும் தேவையானால், வேறு காலத்திற்கு மீண்டும் சந்தா செய்யுங்கள்.\n\n<b>நீங்கள் உண்மையில் பணத்திருப்பி கோர விரும்புகிறீர்களா?</b>",
			"உங்கள் பணத்திருப்பி கோரிக்கை அனுப்பப்பட்டது! தயவுசெய்து காத்திருங்கள்.",
		},
		"te": {
			"<b>రీఫండ్ ఎలా పని చేస్తుంది?</b>\nరీఫండ్ స్థానిక కరెన్సీ \"Stars\"లో ప్రాసెస్ చేయబడుతుంది. ఫండ్స్ క్రియేటర్ ద్వారా మీ Telegram ఛానల్‌లో పోస్ట్ కింద తిరిగి ఇవ్వబడతాయి.\n\n<b>అభ్యర్థన తర్వాత ఫండ్స్ తగ్గించబడతాయా?</b>\nలేదు! మీరు అభ్యర్థన పంపిన వెంటనే మరియు అది సమీక్షలో ఉన్నప్పుడు, సబ్‌స్క్రిప్షన్ రద్దు చేయబడుతుంది, మరియు అకౌంట్‌లో మిగిలిన బ్యాలెన్స్ (ఉపయోగించని రోజుల సంఖ్య) కోసం ఫండ్స్ తిరిగి ఇవ్వబడతాయి.\n\n<b>ఫండ్స్ ఎంత త్వరగా తిరిగి ఇవ్వబడతాయి?</b>\nక్రియేటర్ మీ అభ్యర్థన తర్వాత 10-30 నిమిషాలు (అత్యంత అరుదుగా తరువాత) మీ ప్రొఫైల్‌లో స్పెసిఫై చేసిన Telegram ఛానల్‌లో ఫండ్స్ తిరిగి ఇస్తాడు, లేదా మీ నుండి ఛానల్ లింక్ అడుగుతాడు.\n\n<b>మీరు రీఫండ్‌ను ఎంత తరచుగా అభ్యర్థించవచ్చు?</b>\nప్రతి 3 రోజులకు ఒకసారి మాత్రమే.\n\n<b>నేను ఫండ్స్ భాగాన్ని తిరిగి ఇవ్వవచ్చా?</b>\nమొత్తం మిగిలిన బ్యాలెన్స్ తిరిగి ఇవ్వబడుతుంది. మీకు కేవలం భాగం మాత్రమే అవసరమైతే, వేరే టర్మ్ కోసం మళ్లీ సబ్‌స్క్రైబ్ చేయండి.\n\n<b>మీరు నిజంగా రీఫండ్ అభ్యర్థించాలనుకుంటున్నారా?</b>",
			"మీ రీఫండ్ అభ్యర్థన పంపబడింది! దయచేసి వేచి ఉండండి.",
		},
		"mr": {
			"<b>परतावा कसा काम करतो?</b>\nपरतावा स्थानिक चलन \"Stars\" मध्ये प्रक्रिया केला जातो. निधी क्रिएटर द्वारे तुमच्या Telegram चॅनेलमधील पोस्टखाली परत केला जाईल.\n\n<b>विनंतीनंतर निधी कापला जातो का?</b>\nनाही! तुम्ही विनंती पाठवताच आणि ती पुनरावलोकनात असताना, सदस्यता रद्द केली जाते, आणि खात्यातील उर्वरित शिल्लक (न वापरलेल्या दिवसांची संख्या) साठी निधी परत केला जाईल.\n\n<b>निधी किती लवकर परत केला जाईल?</b>\nक्रिएटर तुमच्या विनंतीनंतर 10-30 मिनिटे (अत्यंत दुर्मिळपणे नंतर) तुमच्या प्रोफाइलमध्ये निर्दिष्ट Telegram चॅनेलमध्ये निधी परत करेल, किंवा तुमच्याकडून चॅनेलचा दुवा मागेल.\n\n<b>तुम्ही किती वेळा परतावा विनंती करू शकता?</b>\nदर 3 दिवसांना एकदा पेक्षा जास्त नाही.\n\n<b>मी निधीचा भाग परत करू शकतो का?</b>\nसंपूर्ण उर्वरित शिल्लक परत केला जातो. जर तुम्हाला फक्त भाग हवा असेल तर, वेगळ्या मुदतीसाठी पुन्हा सदस्यता घ्या.\n\n<b>तुम्ही खरोखर परतावा विनंती करू इच्छिता का?</b>",
			"तुमची परतावा विनंती पाठवली गेली आहे! कृपया प्रतीक्षा करा.",
		},
	}

	return &RefundComponent{text}
}

func (c *RefundComponent) Text(language string) []string {
	return c.text[language]
}
