package components

const RENEW_COMPONENT = "renew"

type RenewComponent struct {
	text map[string][]string
}

func NewRenewComponent() *RenewComponent {
	text := map[string][]string{
		"en": {
			"How long should I extend my subscription for?",
			"Three days",
			"Week",
			"Two weeks",
			"Month",
			"Season",
			"Halfyear",
			"Year",
			"Two years",
		},
		"de": {
			"Wie lange soll ich mein Abonnement verlängern?",
			"Drei Tage",
			"Woche",
			"Zwei Wochen",
			"Monat",
			"Saison",
			"Halbjahr",
			"Jahr",
			"Zwei Jahre",
		},
		"nl": {
			"Hoe lang moet ik mijn abonnement verlengen?",
			"Drie dagen",
			"Week",
			"Twee weken",
			"Maand",
			"Seizoen",
			"Half jaar",
			"Jaar",
			"Twee jaar",
		},
		"sv": {
			"Hur länge ska jag förlänga min prenumeration?",
			"Tre dagar",
			"Vecka",
			"Två veckor",
			"Månad",
			"Säsong",
			"Halvår",
			"År",
			"Två år",
		},
		"no": {
			"Hvor lenge skal jeg forlenge abonnementet mitt?",
			"Tre dager",
			"Uke",
			"To uker",
			"Måned",
			"Sesong",
			"Halvår",
			"År",
			"To år",
		},
		"da": {
			"Hvor længe skal jeg forlænge mit abonnement?",
			"Tre dage",
			"Uge",
			"To uger",
			"Måned",
			"Sæson",
			"Halvår",
			"År",
			"To år",
		},
		"es": {
			"¿Por cuánto tiempo debo extender mi suscripción?",
			"Tres días",
			"Semana",
			"Dos semanas",
			"Mes",
			"Temporada",
			"Medio año",
			"Año",
			"Dos años",
		},
		"fr": {
			"Pour combien de temps dois-je prolonger mon abonnement ?",
			"Trois jours",
			"Semaine",
			"Deux semaines",
			"Mois",
			"Saison",
			"Semestre",
			"Année",
			"Deux ans",
		},
		"pt": {
			"Por quanto tempo devo estender minha assinatura?",
			"Três dias",
			"Semana",
			"Duas semanas",
			"Mês",
			"Temporada",
			"Semestre",
			"Ano",
			"Dois anos",
		},
		"it": {
			"Per quanto tempo devo estendere il mio abbonamento?",
			"Tre giorni",
			"Settimana",
			"Due settimane",
			"Mese",
			"Stagione",
			"Semestre",
			"Anno",
			"Due anni",
		},
		"ru": {
			"На сколько мне продлить подписку?",
			"Три дня",
			"Неделя",
			"Две недели",
			"Месяц",
			"Сезон",
			"Полгода",
			"Год",
			"Два года",
		},
		"ua": {
			"На скільки мені продовжити підписку?",
			"Три дні",
			"Тиждень",
			"Два тижні",
			"Місяць",
			"Сезон",
			"Півроку",
			"Рік",
			"Два роки",
		},
		"pl": {
			"Na jak długo powinienem przedłużyć subskrypcję?",
			"Trzy dni",
			"Tydzień",
			"Dwa tygodnie",
			"Miesiąc",
			"Sezon",
			"Pół roku",
			"Rok",
			"Dwa lata",
		},
		"cs": {
			"Jak dlouho mám prodloužit předplatné?",
			"Tři dny",
			"Týden",
			"Dva týdny",
			"Měsíc",
			"Sezóna",
			"Půl roku",
			"Rok",
			"Dva roky",
		},
		"bg": {
			"Колко дълго трябва да удължа абонамента си?",
			"Три дни",
			"Седмица",
			"Две седмици",
			"Месец",
			"Сезон",
			"Полугодие",
			"Година",
			"Две години",
		},
		"sr": {
			"Колико дуго треба да продужим претплату?",
			"Три дана",
			"Недеља",
			"Две недеље",
			"Месец",
			"Сезона",
			"Полугодиште",
			"Година",
			"Две године",
		},
		"hr": {
			"Koliko dugo trebam produžiti pretplatu?",
			"Tri dana",
			"Tjedan",
			"Dva tjedna",
			"Mjesec",
			"Sezona",
			"Polugodište",
			"Godina",
			"Dvije godine",
		},
		"sk": {
			"Ako dlho mám predĺžiť predplatné?",
			"Tri dni",
			"Týždeň",
			"Dva týždne",
			"Mesiac",
			"Sezóna",
			"Polrok",
			"Rok",
			"Dva roky",
		},
		"sl": {
			"Kako dolgo naj podaljšam naročnino?",
			"Tri dni",
			"Teden",
			"Dva tedna",
			"Mesec",
			"Sezona",
			"Pol leta",
			"Leto",
			"Dve leti",
		},
		"lt": {
			"Kiek laiko turėčiau pratęsti prenumeratą?",
			"Trys dienos",
			"Savaitė",
			"Dvi savaitės",
			"Mėnuo",
			"Sezonas",
			"Pusmetis",
			"Metai",
			"Dveji metai",
		},
		"lv": {
			"Cik ilgi man jāpagarinās abonements?",
			"Trīs dienas",
			"Nedēļa",
			"Divas nedēļas",
			"Mēnesis",
			"Sezona",
			"Pusgads",
			"Gads",
			"Divi gadi",
		},
		"et": {
			"Kui kauaks peaksin tellimust pikendama?",
			"Kolm päeva",
			"Nädal",
			"Kaks nädalat",
			"Kuu",
			"Hooaeg",
			"Poolaasta",
			"Aasta",
			"Kaks aastat",
		},
		"fi": {
			"Kuinka kauan minun pitäisi jatkaa tilaustani?",
			"Kolme päivää",
			"Viikko",
			"Kaksi viikkoa",
			"Kuukausi",
			"Kausi",
			"Puolivuosi",
			"Vuosi",
			"Kaksi vuotta",
		},
		"el": {
			"Για πόσο καιρό πρέπει να επεκτείνω τη συνδρομή μου;",
			"Τρεις ημέρες",
			"Εβδομάδα",
			"Δύο εβδομάδες",
			"Μήνας",
			"Σεζόν",
			"Εξάμηνο",
			"Έτος",
			"Δύο χρόνια",
		},
		"ro": {
			"Cât timp ar trebui să prelungesc abonamentul?",
			"Trei zile",
			"Săptămână",
			"Două săptămâni",
			"Lună",
			"Sezon",
			"Jumătate de an",
			"An",
			"Doi ani",
		},
		"hu": {
			"Mennyi időre hosszabbítsam meg az előfizetésemet?",
			"Három nap",
			"Hét",
			"Két hét",
			"Hónap",
			"Szezon",
			"Félév",
			"Év",
			"Két év",
		},
		"ar": {
			"كم من الوقت يجب أن أمدد اشتراكي؟",
			"ثلاثة أيام",
			"أسبوع",
			"أسبوعان",
			"شهر",
			"موسم",
			"نصف عام",
			"عام",
			"عامان",
		},
		"fa": {
			"اشتراکم را برای چه مدت تمدید کنم؟",
			"سه روز",
			"هفته",
			"دو هفته",
			"ماه",
			"فصل",
			"نیم‌سال",
			"سال",
			"دو سال",
		},
		"tr": {
			"Aboneliğimi ne kadar süre uzatmalıyım?",
			"Üç gün",
			"Hafta",
			"İki hafta",
			"Ay",
			"Sezon",
			"Yarım yıl",
			"Yıl",
			"İki yıl",
		},
		"he": {
			"לכמה זמן עלי להאריך את המנוי שלי?",
			"שלושה ימים",
			"שבוע",
			"שבועיים",
			"חודש",
			"עונה",
			"חצי שנה",
			"שנה",
			"שנתיים",
		},
		"zh": {
			"我应该将订阅延长多久？",
			"三天",
			"周",
			"两周",
			"月",
			"季节",
			"半年",
			"年",
			"两年",
		},
		"ja": {
			"サブスクリプションをどれくらい延長すればよいですか？",
			"3日",
			"週",
			"2週間",
			"月",
			"シーズン",
			"半年",
			"年",
			"2年",
		},
		"ko": {
			"구독을 얼마나 연장해야 하나요?",
			"3일",
			"주",
			"2주",
			"월",
			"시즌",
			"반년",
			"년",
			"2년",
		},
		"vi": {
			"Tôi nên gia hạn đăng ký trong bao lâu?",
			"Ba ngày",
			"Tuần",
			"Hai tuần",
			"Tháng",
			"Mùa",
			"Nửa năm",
			"Năm",
			"Hai năm",
		},
		"th": {
			"ฉันควรต่ออายุการสมัครสมาชิกนานเท่าไหร่?",
			"สามวัน",
			"สัปดาห์",
			"สองสัปดาห์",
			"เดือน",
			"ฤดูกาล",
			"ครึ่งปี",
			"ปี",
			"สองปี",
		},
		"id": {
			"Berapa lama saya harus memperpanjang langganan saya?",
			"Tiga hari",
			"Minggu",
			"Dua minggu",
			"Bulan",
			"Musim",
			"Setengah tahun",
			"Tahun",
			"Dua tahun",
		},
		"ms": {
			"Berapa lama saya perlu panjangkan langganan saya?",
			"Tiga hari",
			"Minggu",
			"Dua minggu",
			"Bulan",
			"Musim",
			"Setengah tahun",
			"Tahun",
			"Dua tahun",
		},
		"tl": {
			"Gaano katagal ko dapat pahabain ang aking subscription?",
			"Tatlong araw",
			"Linggo",
			"Dalawang linggo",
			"Buwan",
			"Panahon",
			"Kalagitnaan ng taon",
			"Taon",
			"Dalawang taon",
		},
		"hi": {
			"मुझे अपनी सदस्यता कितने समय के लिए बढ़ानी चाहिए?",
			"तीन दिन",
			"सप्ताह",
			"दो सप्ताह",
			"महीना",
			"मौसम",
			"अर्ध वर्ष",
			"वर्ष",
			"दो वर्ष",
		},
		"ur": {
			"مجھے اپنی سبسکرپشن کو کتنی دیر تک بڑھانا چاہیے؟",
			"تین دن",
			"ہفتہ",
			"دو ہفتے",
			"ماہ",
			"سیزن",
			"آدھا سال",
			"سال",
			"دو سال",
		},
		"bn": {
			"আমি আমার সাবস্ক্রিপশন কতক্ষণের জন্য বাড়াব?",
			"তিন দিন",
			"সপ্তাহ",
			"দুই সপ্তাহ",
			"মাস",
			"ঋতু",
			"অর্ধবর্ষ",
			"বছর",
			"দুই বছর",
		},
		"ta": {
			"எனது சந்தாவை எவ்வளவு காலம் நீட்டிக்க வேண்டும்?",
			"மூன்று நாட்கள்",
			"வாரம்",
			"இரண்டு வாரங்கள்",
			"மாதம்",
			"பருவம்",
			"அரை ஆண்டு",
			"ஆண்டு",
			"இரண்டு ஆண்டுகள்",
		},
		"te": {
			"నా సబ్‌స్క్రిప్షన్‌ను ఎంతకాలం పొడిగించాలి?",
			"మూడు రోజులు",
			"వారం",
			"రెండు వారాలు",
			"నెల",
			"సీజన్",
			"అర్ధ సంవత్సరం",
			"సంవత్సరం",
			"రెండు సంవత్సరాలు",
		},
		"mr": {
			"मी माझी सदस्यता किती काळासाठी वाढवावी?",
			"तीन दिवस",
			"आठवडा",
			"दोन आठवडे",
			"महिना",
			"हंगाम",
			"अर्धा वर्ष",
			"वर्ष",
			"दोन वर्षे",
		},
	}

	return &RenewComponent{text}
}

func (c *RenewComponent) Text(language string) []string {
	return c.text[language]
}
